Remove PackageHub Activating code for test w3m
os-autoinst/os-autoinst-distri-opensuse pull request #10964
Opened 2020-09-09 09:03 UTC by lilyeyes

Remove PackageHub Activating code for test w3m

- Related ticket: https://progress.opensuse.org/issues/70492
- Needles: NA
- Verification run: http://openqa.suse.de/tests/4662978#

2020-09-09 09:08 UTC, okurz requested changes
I wonder why you need this change. 
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. Also please rebase because there should be no "merge" commits in personal feature branches before merging into master.

I wonder what is the purpose of the `zypper search` line because this does not look like it has a direct relation to running w3m if the fips pattern exists or not. Also you are duplicating the code. Maybe that call is not necessary at all for w3m.

2020-09-09 09:22 UTC, lilyeyes commented
> I wonder why you need this change.
Test case "w3m" failed on "Packagehub" is not ready now" but w3m pkg is not in packagehub now, so I deleted the "setup_web_browser_env" as it activates "Packagehub".
See the related poo for more info.
> The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages. Also please rebase because there should be no "merge" commits in personal feature branches before merging into master.
> 
I left some message to the related poo, I think reviewer should read/understand the poo.

> I wonder what is the purpose of the `zypper search` line because this does not look like it has a direct relation to running w3m if the fips pattern exists or not. Also you are duplicating the code. Maybe that call is not necessary at all for w3m.

It makes sure that the "fips" pattern should be existed.

2020-09-09 11:32 UTC, okurz commented
> > I wonder why you need this change.
> 
> Test case "w3m" failed on "Packagehub is not ready" but w3m pkg is not in packagehub now, so I deleted the "setup_web_browser_env" as it activates "Packagehub".
> See the related poo for more info.

Maybe the package hub activation code is still necessary for other versions of SLE then?

> > The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see [commit.style](https://commit.style/) or [http://chris.beams.io/posts/git-commit](http://chris.beams.io/posts/git-commit/) as a helpful guide how to write good commit messages. Also please rebase because there should be no "merge" commits in personal feature branches before merging into master.
> 
> Rebased. Thanks for the finding.
> I left some message to the related poo, I think reviewer should read/understand the poo.
> We also need to added them to PR, right?

I recommend you put more details in the *git commit message* as the git log should have enough information for anyone looking in the git history to understand why changes have been done and what needs to be kept in mind when further changes will be done in the future.

> > I wonder what is the purpose of the `zypper search` line because this does not look like it has a direct relation to running w3m if the fips pattern exists or not. Also you are duplicating the code. Maybe that call is not necessary at all for w3m.
> 
> It makes sure that the "fips" pattern should be existed.

Yes, I understand that. But why should a properly designed test for w3m care about the fips pattern? At least judging from the name of w3m that should focus on testing w3m and not care about a fips pattern.

2020-09-10 03:24 UTC, lilyeyes commented
> Maybe the package hub activation code is still necessary for other versions of SLE then?
> 

Totally agree with your concerns on this, I have tried to check on sle12sp5 but found no vm available or qcow in openQA now, also maintenance QA did not use/run test case `w3m_https`.
So, it is really time consuming so sometimes I prefer to fix the issue when introducing issue on other versions.
Also @jouyingbin helped to check the pkg `w3m` is in `SLES12-SP5-Pool` but not `Packagehub` now. Then there is no issue now.
 
> > > The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see [commit.style](https://commit.style/) or [http://chris.beams.io/posts/git-commit](http://chris.beams.io/posts/git-commit/) as a helpful guide how to write good commit messages. Also please rebase because there should be no "merge" commits in personal feature branches before merging into master.
> > 

Got it. :+1: 

> > 
> > Rebased. Thanks for the finding.
> > I left some message to the related poo, I think reviewer should read/understand the poo.
> > We also need to added them to PR, right?
> 
> I recommend you put more details in the _git commit message_ as the git log should have enough information for anyone looking in the git history to understand why changes have been done and what needs to be kept in mind when further changes will be done in the future.
> 

Got it, thanks :+1: 

> > > I wonder what is the purpose of the `zypper search` line because this does not look like it has a direct relation to running w3m if the fips pattern exists or not. Also you are duplicating the code. Maybe that call is not necessary at all for w3m.
> > 
> > 
> > It makes sure that the "fips" pattern should be existed.
> 
> Yes, I understand that. But why should a properly designed test for w3m care about the fips pattern? At least judging from the name of w3m that should focus on testing w3m and not care about a fips pattern.

Our test case name is "w3m_https" (verify w3m can access https servers with fips enabled on client)
But if without " fips enabled" this test case can be reused by others.

2020-09-10 05:21 UTC, okurz approved these changes
> So, it is really time consuming

I am sorry if this was the case for you. I guess it could have been just as simple as:

```perl
if (is_sle('<=15-sp2')) {
    setup_web_browser_env();
}
else {
    zypper_call("--no-refresh --no-gpg-checks search -it pattern fips") if get_var('FIPS_ENABLED');
}
```

but if you think there is more to it, I could be wrong.

2020-09-10 05:21 UTC, merged

2020-09-10 06:01 UTC, lilyeyes commented
> > So, it is really time consuming
> 
> I am sorry if this was the case for you. I guess it could have been just as simple as:
> 
> ```perl
> if (is_sle('<=15-sp2')) {
>     setup_web_browser_env();
> }
> else {
>     zypper_call("--no-refresh --no-gpg-checks search -it pattern fips") if get_var('FIPS_ENABLED');
> }
> ```
> 
> but if you think there is more to it, I could be wrong.
Yes the code is similar/same. I mean I have to verify at lease on 15sp1 this code works but 15sp1 qcows are not easy to found in openQA or other ways.

2020-09-10 06:07 UTC, jouyingbin approved these changes
LGTM. Thanks for the change.