Increase default value of timeout to assert root-console
os-autoinst/os-autoinst-distri-opensuse pull request #10973
Opened 2020-09-10 06:09 UTC by lemon-suse

The default value for timeout of assert_screen for root-console is 30 which is not enough, so just increase it to 60 to fix this issue.

- Related ticket: https://progress.opensuse.org/issues/71149
- Needles: N/A
- Verification run: http://openqa.nue.suse.com/tests/4669062#

2020-09-10 06:21 UTC, tinawang123 commented
LGTM

2020-09-10 06:21 UTC, tinawang123 approved these changes

2020-09-10 06:52 UTC, okurz requested changes
With a change with this big impact there should definitely be a more detailed git commit message. And please do not just state the obvious in the git commit message line but something that transports the meaning of why this change is needed or helpul.

The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

2020-09-10 06:58 UTC, okurz commented
The specific job you mentioned failed after some heavy weight snapper action. So I recommend you try to wait for that process to settle down and not rely on the timeout of `select_console` which was never designed to cover cases like these.

@tinawang123 for future reviews please keep in mind not only "fixes my case". As a reviewer for os-autoinst-distri-opensuse you have the responsibility for the state of code in the complete repository which is far bigger than just the area of SLE migration.

2020-09-10 09:08 UTC, lemon-suse commented
> The specific job you mentioned failed after some heavy weight snapper action. So I recommend you try to wait for that process to settle down and not rely on the timeout of `select_console` which was never designed to cover cases like these.
> 
> @tinawang123 for future reviews please keep in mind not only "fixes my case". As a reviewer for os-autoinst-distri-opensuse you have the responsibility for the state of code the complete repository which is far bigger than just the area of SLE migration.

Hi Oliver, thanks for your comments. The issue is caused by snapper action when try to run power action to reboot. Yes, we can wait the snapper process to settle down, I just afraid in the future there may be other process block here then we need wait more uncertain process which will make code in a mess.
Another thinking, in fact as my understanding the action of use snapper to create snappershot should be part of 'zypper migration, while it is non-block process which cause zypper migration return but snapper still ongoing. If zypper migration wait snapper finished to return, then no this issue.

2020-09-10 13:56 UTC, lemon-suse commented
> I suggest to always try to keep tests simple and design them from the high-level point of view of what a user would also do. So a user does not actually _know_ and should not need to know that snapper is the culprit. Just wait longer for "root-console", that is ok but do not impact _every_ other test with your change. For example you can do:
> 
> ```perl
> select_console … => await_console => 0;
> assert_screen 'root-console', 600;  # long time for snapper to settle down
> ```

Hi Oliver, thanks. I have updated code following your suggestion and got the verify log, http://openqa.nue.suse.com/tests/4670128#step/zypper_migration/12.

2020-09-10 14:08 UTC, lemon-suse commented
> With a change with this big impact there should definitely be a more detailed git commit message. And please do not just state the obvious in the git commit message line but something that transports the meaning of why this change is needed or helpul.
> 
> The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

Thanks, updated the commit also.

2020-09-10 14:20 UTC, okurz commented
there is a conflict. You need to rebase.

2020-09-11 05:50 UTC, okurz approved these changes

2020-09-11 07:46 UTC, lemon-suse commented
Already got approve from Oliver, so I will merge it.

2020-09-11 07:46 UTC, merged