Skip pulling container images from docker.io
os-autoinst/os-autoinst-distri-opensuse pull request #11368
Opened 2020-11-09 20:24 UTC by jlausuch

Alpine and Hello-world containers are pulled from docker.io,
since November 2, 2020 the pull rate was limited so many test
are failing when pulling these images. The idea of this PR
is to skip those images until we find a workaround, like
mirroring those images to some registry we have more control
e.g. registry.opensuse.org

Example of failure: https://openqa.suse.de/tests/4962111#step/podman/18
This is happening in many places now. 

This PR is to be reverted when we find a workaround to not pull
from docker.io

2020-11-09 20:30 UTC, mloviska commented
Can we create a #poo for this with for instance one week deadline? Maybe a bit higher prio, wdyt?

2020-11-09 20:30 UTC, mloviska approved these changes

2020-11-09 21:54 UTC, jlausuch commented
> Can we create a #poo for this with for instance one week deadline? Maybe a bit higher prio, wdyt?

there is one [poo#76993](https://progress.opensuse.org/issues/76993)

2020-11-09 21:56 UTC, pdostal approved these changes

2020-11-09 22:06 UTC, b10n1k commented on lib/containers/utils.pm
> +    #assert_script_run("$runtime image pull alpine:$alpine_image_version", timeout => 300);
why not a soft_fail to make it visible in the test?

2020-11-09 22:09 UTC, b10n1k requested changes
There is another solution that actually, which it needs some discussion tho. we can `save` the images and upload them to the git. Then we can pull from there. See https://docs.docker.com/engine/reference/commandline/build/#git-repositories

2020-11-09 22:29 UTC, pdostal commented
> There is another solution that actually, which it needs some discussion tho. we can `save` the images and upload them to the git. Then we can pull from there. See https://docs.docker.com/engine/reference/commandline/build/#git-repositories

Good idea! We may do this as well. But we should test `docker pull` at least somewhere.

2020-11-10 07:21 UTC, mloviska commented
> > Can we create a #poo for this with for instance one week deadline? Maybe a bit higher prio, wdyt?
> 
> there is one [poo#76993](https://progress.opensuse.org/issues/76993)

ah, late hour. Sorry! :) I am ready to merge

2020-11-10 07:42 UTC, jlausuch commented
> There is another solution that actually, which it needs some discussion tho. we can `save` the images and upload them to the git. Then we can pull from there. See https://docs.docker.com/engine/reference/commandline/build/#git-repositories

Let's investigate this. For now, we can just skip those tests until we find a solution.

2020-11-10 07:45 UTC, mloviska commented
> > There is another solution that actually, which it needs some discussion tho. we can `save` the images and upload them to the git. Then we can pull from there. See https://docs.docker.com/engine/reference/commandline/build/#git-repositories
> 
> Let's investigate this. For now, we can just skip those tests until we find a solution.

+1

2020-11-10 09:25 UTC, jlausuch commented
updated with soft-failures

2020-11-10 10:41 UTC, b10n1k commented
i guess this is a quick solution. I will just leave the idea here for reference. ideally we should check the rate limits stats and act appropriately. ex: when limits exceed show soft_fail. rate limits can be checked as it is described here https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/. @jlausuch let me know if you "like" the idea and if you need a ticket for this, so we do not block this one

2020-11-10 11:11 UTC, jlausuch commented
> i guess this is a quick solution here. So I will just leave the idea here for reference. ideally we should check the rate limits stats and act appropriately. ex: when limits exceed show soft_fail. rate limits can be checked as it is described here https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/. @jlausuch let me know if you "like" the idea and if you need a ticket for this, so we do not block this one

I don't like to depend on some random limits. We should fix the problem that works always :)

2020-11-10 11:51 UTC, foursixnine commented
> i guess this is a quick solution here. So I will just leave the idea here for reference. ideally we should check the rate limits stats and act appropriately. ex: when limits exceed show soft_fail. rate limits can be checked as it is described here https://www.docker.com/blog/checking-your-current-docker-pull-rate-limits-and-status/. @jlausuch let me know if you "like" the idea and if you need a ticket for this, so we do not block this one

Probably the cost of implementing this logic, is higher than creating the containers in openSUSE registry for instance... :)

2020-11-10 11:51 UTC, foursixnine approved these changes

2020-11-10 11:52 UTC, merged

2020-11-10 11:53 UTC, foursixnine commented
@jlausuch One thing that I see here, is that the failure is unconditional for whatever error, instead of the rate limit specific condition... (just 2c, it's still good enough for now :))

2020-11-10 11:55 UTC, jlausuch commented
> @jlausuch One thing that I see here, is that the failure is unconditional for whatever error, instead of the rate limit specific condition... (just 2c, it's still good enough for now :))

yeah, I know. I have put deadline in the progress ticket to revert this again, so this is for sure a temporary workaround. Thanks for pointing that out.