[WIP] Add jsc#SLE- condition in record_soft_failure in Makefile
os-autoinst/os-autoinst-distri-opensuse pull request #11519
Opened 2020-12-01 03:14 UTC by jouyingbin

Fix the SLE- prefix missing in record_soft_failure

- Related ticket: https://progress.opensuse.org/issues/xyz
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

2020-12-01 09:14 UTC, okurz requested changes
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [pr-last](http://github.com/okurz/scripts/tree/master/pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

2020-12-02 08:49 UTC, jouyingbin commented
> What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has _only_ the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

Yes, I totally agree with you. I will keep in mind that git commit message is more important and more detail is better. I have updated. Thanks for reminder.

> 
> I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [pr-last](https://github.com/okurz/scripts/tree/master/pr-last) to create a PR with proper description for these simple one-commit PRs:
> 
> ```shell
> $ cat $(which git-pr-last )
> #!/bin/sh -e
> target="${target:-"$USER"}"
> git push $target && git show --no-patch --format=%B | hub pull-request -F -
> ```

Thanks for your information, it's really useful for me. I will learn about it more later. :+1:

2020-12-03 03:50 UTC, jouyingbin commented
Hello @okurz ,
Would you please help to review and merge my PR while you are available? Thanks a lot. :)

2020-12-03 15:29 UTC, okurz approved these changes

2020-12-03 15:29 UTC, merged