Fix container URLs for MicroOS 15.2
os-autoinst/os-autoinst-distri-opensuse pull request #11540
Opened 2020-12-03 08:52 UTC by lnussel

Fixes unknown container URL on MicroOS 15.2, see
https://openqa.opensuse.org/tests/1492452#step/podman_image/2

Can't really verify as I don't have an openQA test setup atm.

2020-12-03 09:07 UTC, Vogtinator commented
> Can't really verify as I don't have an openQA test setup atm.

```
openqa-clone-job --skip-chained-deps --within-instance https://openqa.opensuse.org 1492452 _GROUP=38 CASEDIR=https://github.com/lnussel/os-autoinst-distri-opensuse.git#microos
```
Created job #1493414: microos-15.2-MicroOS-Image-ContainerHost-x86_64-Build71.1-container-host@64bit-2G -> https://openqa.opensuse.org/t1493414

2020-12-03 09:12 UTC, Vogtinator requested changes

2020-12-03 09:12 UTC, Vogtinator commented on lib/suse_container_urls.pm
> +    elsif ((is_leap(">15.0" || is_microos(">15.0")) && (check_var('ARCH', 'aarch64') || check_var('ARCH', 'arm'))) {
```suggestion
    elsif ((is_leap(">15.0") || is_microos(">15.0")) && (check_var('ARCH', 'aarch64') || check_var('ARCH', 'arm'))) {
```

to fix

```
[0msyntax error at /var/lib/openqa/pool/11/os-autoinst-distri-opensuse/lib/suse_container_urls.pm line 89, near ") {"
syntax error at /var/lib/openqa/pool/11/os-autoinst-distri-opensuse/lib/suse_container_urls.pm line 93, near "elsif"
```

2020-12-04 13:45 UTC, Vogtinator commented
New VR: https://openqa.opensuse.org/tests/1494736

2020-12-04 13:46 UTC, lnussel commented
that way to clone jobs is awesome, can we have that in the ui please? :)

2020-12-04 13:55 UTC, Vogtinator commented
> that way to clone jobs is awesome, can we have that in the ui please? :)

Or even better, https://progress.opensuse.org/issues/44327#note-4

(@okurz is there a ticket for ^ specifically somewhere?)

2020-12-04 14:12 UTC, okurz commented
> > that way to clone jobs is awesome, can we have that in the ui please? :)
> 
> Or even better, [progress.opensuse.org/issues/44327#note-4](https://progress.opensuse.org/issues/44327#note-4)
> 
> (@okurz is there a ticket for ^ specifically somewhere?)

Sorry, I am not sure what specifically you want a ticket for. https://progress.opensuse.org/issues/44327 is the original ticket for "trigger custom git repos", yes. And the official documentation for that is
http://open.qa/docs/#_triggering_tests_based_on_an_any_remote_git_refspec_or_open_github_pull_request


> that way to clone jobs is awesome, can we have that in the ui please? :)

Well, this is already supported by just defining the according test variables in the openQA web UI, e.g. `CASEDIR=git@github.com:os-autoinst/os-autoinst-distri-opensuse.git` as part of a medium, test suite, job template, etc.

Some further smaller ideas are mentioned in https://progress.opensuse.org/issues/65271 and you are welcome to add more.

Or did I get you wrong?

2020-12-04 14:17 UTC, lnussel commented
For someone not into openQA development much I'd naively simply look for a "fix me on github" button next to the job restart button in openQA :-) Thanks for the pointers though, wil have to remember for next time

2020-12-04 14:20 UTC, Vogtinator commented
> > that way to clone jobs is awesome, can we have that in the ui please? :)
> 
> Well, this is already supported by just defining the according test variables in the openQA web UI, e.g. `CASEDIR=git@github.com:os-autoinst/os-autoinst-distri-opensuse.git` as part of a medium, test suite, job template, etc.
>
> Some further smaller ideas are mentioned in https://progress.opensuse.org/issues/65271 and you are welcome to add more.
> 
> Or did I get you wrong?

I couldn't find anything regarding the "mention @openQA to clone a job" idea you had on that page. Is that anywhere?

IMO that makes more sense than adding a button in the openQA Web UI, as the verification run has to be mentioned on the PR anyway.

2020-12-04 14:21 UTC, okurz commented
> For someone not into openQA development much I'd naively simply look for a "fix me on github" button next to the job restart button in openQA :-)

Ok, I am open for the idea. What should that button do then, open the branch creation github web page on a personal github fork of the original repo?

2020-12-04 14:56 UTC, Vogtinator approved these changes
VR is green

2020-12-07 15:58 UTC, merged