[WIP] Add is_leap('>15.2') in firewalld.pm
os-autoinst/os-autoinst-distri-opensuse pull request #11599
Opened 2020-12-10 15:40 UTC by michelmno

to avoid firewalld test failure on first leap 15.3 openQA tests:
x86_64:  https://openqa.opensuse.org/tests/1500066#step/firewalld/35
aarch64: https://openqa.opensuse.org/tests/1500092#step/firewalld/35
ppc64le: https://openqa.opensuse.org/tests/1500158#step/firewalld/35

- Related ticket: none
- Needles: none
- Verification run: not yet

2020-12-11 05:21 UTC, okurz requested changes

2020-12-11 05:21 UTC, okurz commented on tests/console/firewalld.pm
> +    if (is_tumbleweed || is_sle('15-SP3+') || is_leap('15.3+')) {
Unfortunately this was already done inefficiently in before.

Our tests should always consider openSUSE Tumbleweed as the default product without a version. That means any differing behaviour should have an explicit exclude rule for the "older products" and potentially an explanation why the behaviour should differ. You can try to negate the logic check

```suggestion
    if (!is_sle('<15-SP3') && !is_leap('<15.3')) {
```

@foursixnine you introduced the "15-SP3+" in https://github.com/michelmno/os-autoinst-distri-opensuse/commit/7152ed2f85e49676f730d0d25c1cfa39de02ee32 and @atanno you introduced the "is_tumbleweed" in https://github.com/michelmno/os-autoinst-distri-opensuse/commit/0e5f7e6a2e91f66145ff782276d488f0f5065146

2020-12-11 12:19 UTC, okurz commented
please change the git commit subject message according to your updated change. Also rebase to get a fix for tidy

2020-12-11 13:21 UTC, michelmno commented
> please change the git commit subject message according to your updated change. Also rebase to get a fix for tidy

commit subject updated

2020-12-11 13:33 UTC, okurz approved these changes

2021-01-26 07:40 UTC, okurz approved these changes
great! :)

2021-01-26 07:40 UTC, merged