Use SUSEConnect command to registrate NVIDIA module
os-autoinst/os-autoinst-distri-opensuse pull request #11695
Opened 2021-01-06 02:58 UTC by tinawang123

Use SUSEConnect command to registrate NVIDIA module, need command:
SUSEConnect -p sle-module-NVIDIA-compute/15/aarch64

- Related ticket: https://progress.opensuse.org/issues/81766
- Verification run: https://openqa.suse.de/tests/5252175#details

2021-01-07 05:59 UTC, lemon-suse commented on lib/registration.pm
> +            if ((grep(/$name/, @SLE12_MODULES) and is_sle('<15')) || grep(/$name/, @SLE15_MODULES)) {
It is better to add condition of is_sle('15+') for SLE15_MODULES in case some modules will be in version 12 and 15.

2021-01-07 06:44 UTC, lemon-suse approved these changes

2021-01-07 06:49 UTC, chcao approved these changes
LGTM

2021-04-07 09:15 UTC, okurz requested changes
s/registrate/register/

2021-04-14 02:49 UTC, closed without merging