Add test for scientific python packages
os-autoinst/os-autoinst-distri-opensuse pull request #11699
Opened 2021-01-06 10:41 UTC by grisu48

This commit adds a test for numpy and scipy packages on openSUSE and
SLE>=15

- Related ticket: https://progress.opensuse.org/issues/81376
- Verification runs: [Tumbleweed](http://duck-norris.qam.suse.de/tests/4423) | [SLE15-SP2](http://duck-norris.qam.suse.de/tests/4422) | [SLE15-SP1](http://duck-norris.qam.suse.de/tests/4421) | [SLE15](http://duck-norris.qam.suse.de/tests/4420)

2021-01-06 12:57 UTC, dzedro commented on tests/console/python_scientific.pm
> +    # unregister SDK
is not sdk and comment not really needed

2021-01-06 13:02 UTC, dzedro commented on tests/console/python_scientific.pm
> +    #$self->select_serial_terminal;
Why not serial console ?

2021-01-06 13:03 UTC, grisu48 commented on tests/console/python_scientific.pm
> +    #$self->select_serial_terminal;
Updated

2021-01-06 13:15 UTC, dzedro commented on tests/console/python_scientific.pm
> +use registration qw(cleanup_registration register_product add_suseconnect_product get_addon_fullname remove_suseconnect_product);
From `version_utils` you use only `is_sle`, people tend to don't define the list of subroutines if it's too long.
Do as you like. :)

2021-01-06 13:20 UTC, dzedro commented on lib/main_common.pm
> +    loadtest 'console/python-scientific' unless (is_sle("<15"));
Just curious when this, I guess for somebody unnecessary complicated, unless condition gang started :)

2021-01-06 13:34 UTC, dzedro approved these changes

2021-01-06 15:57 UTC, pdostal requested changes

2021-01-06 15:57 UTC, pdostal commented on tests/console/python_scientific.pm
> +    cleanup();
```suggestion
    cleanup();
    $self->SUPER::post_fail_hook;
```

2021-01-06 15:57 UTC, pdostal commented on tests/console/python_scientific.pm
> +    my $logfile = "output.txt";
```suggestion
    my $logfile = "output.txt";
    record_info($script, "Running $script python script");
```

2021-01-06 15:57 UTC, pdostal commented on tests/console/python_scientific.pm
> +    cleanup();
```suggestion
    cleanup();
    $self->SUPER::post_run_hook;
```

2021-01-06 16:47 UTC, grisu48 commented on tests/console/python_scientific.pm
> +    my $logfile = "output.txt";
This is a good idea!

2021-01-06 17:38 UTC, pdostal commented on tests/console/python_scientific.pm
> +    cleanup();
WDYT?

2021-01-07 07:18 UTC, grisu48 commented on tests/console/python_scientific.pm
> +    cleanup();
Done

2021-01-07 09:41 UTC, pdostal approved these changes

2021-01-07 09:42 UTC, merged

2021-01-08 08:50 UTC, Vogtinator commented
This broke main_common.pm: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11712

2021-01-08 13:00 UTC, ostruzina commented
It looks like it needs a little bit more looking into: https://openqa.suse.de/tests/5259741#step/python_scientific/19

(results from SLE15-SP1 and SLE15-SP2 are not available yet because the test did not run due to a broken aggregate build)