Fix rm bootloader centos
os-autoinst/os-autoinst-distri-opensuse pull request #11890
Opened 2021-02-03 13:51 UTC by b10n1k

This is to remove the boot_to_desktop from the scheduling                                                                                                                                                                                    
as the bootloader_start can handle the boot process from                                                                                                                                                                                     
pre-installed qcows

- Related ticket: https://progress.opensuse.org/issues/88440
- Verification run: https://openqa.suse.de/tests/overview?distri=sle&version=15-SP3&build=b10n1k%2Fos-autoinst-distri-opensuse%23fix_rm_bootloader_centos

2021-02-03 14:09 UTC, asmorodskyi commented
I think you mess up something with git , this commit does not needed https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11890/commits/e1dda2ab31231915070fa22df59982889ea0fe98

2021-02-03 14:10 UTC, asmorodskyi requested changes
One of commits needs to be removed from this PR

2021-02-03 14:11 UTC, b10n1k commented
> I think you mess up something with git , this commit does not needed [e1dda2a](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/e1dda2ab31231915070fa22df59982889ea0fe98)

i did. sorry. i will fix

2021-02-03 14:15 UTC, b10n1k commented
> One of commits needs to be removed from this PR

Done

2021-02-03 14:47 UTC, merged

2021-02-04 12:34 UTC, rwx788 commented
Broke https://openqa.opensuse.org/tests/1617551

2021-02-04 12:34 UTC, DimStar77 commented
New failure: https://openqa.opensuse.org/tests/1617551

2021-02-04 12:39 UTC, DimStar77 commented
>     * Related ticket: https://progress.opensuse.org/issues/88440

And I want to air frustration: why is any ticketing system collecting issues for an opensource project (os-autoinst and os-autoinst-distri-opensuse) having any kind of restrictive access policy? this is bonkers!

2021-02-04 15:02 UTC, asmorodskyi commented
@DimStar77  https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/11902