Add test for flatpak
os-autoinst/os-autoinst-distri-opensuse pull request #11943
Opened 2021-02-11 13:00 UTC by grisu48

Adds flatpak openQA test for Tumbleweed.
We run some basic flatpak commands, install and run gimp to ensure flatpak is working properly.

- Related ticket: https://progress.opensuse.org/issues/68636
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/713
- Verification run: [http://duck-norris.qam.suse.de/t5051](http://duck-norris.qam.suse.de/tests/5051#step/flatpak/28)

2021-02-11 13:54 UTC, ggkioulis approved these changes
Nice initiative!

2021-02-11 14:08 UTC, a-kpappas requested changes

2021-02-11 14:08 UTC, a-kpappas commented on tests/x11/flatpak.pm
> +    select_console 'root-console';
AFAIK the serial console is faster.

2021-02-11 14:15 UTC, grisu48 commented on lib/main_common.pm
> +        loadtest 'x11/flatpak' if (is_opensuse);
Gnome should be sufficient to test the GUI component, don't you think? We could extend to KDE though.

2021-02-12 10:04 UTC, a-kpappas commented on lib/main_common.pm
> +        loadtest 'x11/flatpak' if (is_opensuse);
I guess that could be done in another PR.

2021-02-12 10:05 UTC, a-kpappas approved these changes

2021-02-12 10:26 UTC, merged

2021-02-15 08:21 UTC, ggardet commented
This is broken.
* x86_64: missing needle: https://openqa.opensuse.org/tests/1628202#step/flatpak/41
* aarch64: `steam` not found: https://progress.opensuse.org/issues/88582

2021-02-15 08:27 UTC, grisu48 commented
> This is broken.
> 
>     * x86_64: missing needle: https://openqa.opensuse.org/tests/1628202#step/flatpak/41
> 
>     * aarch64: `steam` not found: https://progress.opensuse.org/issues/88582

Working on it: https://progress.opensuse.org/issues/88585