Fix issues with InfiniBand testing
os-autoinst/os-autoinst-distri-opensuse pull request #11952
Opened 2021-02-12 13:27 UTC by frankenmichl

This PR contains two fixes for the InfiniBand testsuite. 
First, we need to install rdma-core package earlier to avoid race conditions after package installation. This allows the testsuite to run and find an active port.
Second, improve logfiles created for both nodes, so we have dmesg and systemd logs for both master and slave, whis is sometimes needed for error diagnosis and bug reporting

See the verification run, which gets past phase 1 now and can execute the entire testsuite.

- Related ticket: https://progress.opensuse.org/issues/88539
- Needles: https://gitlab.suse.de/openqa/os-autoinst-needles-sles/-/merge_requests/1487
- Verification run: http://baremetal-support.qa.suse.de/tests/766 and http://baremetal-support.qa.suse.de/tests/767

2021-02-12 15:46 UTC, SergioAtSUSE requested changes

2021-02-12 15:46 UTC, SergioAtSUSE commented on tests/installation/select_packages.pm
> +    return unless check_screen 'inst-overview-blocked';
The **assert_screen** is important. The test is expecting to test a behavior from yast overview to block the installation if a required package i.e. & e.g. grub2 is not selected. See https://openqa.suse.de/tests/5443793#step/select_packages/44 (please, add verification run for that scenario too)

Removing the assert screen and returning will cause false negatives when a regression happens.

If the intention is to misuse this module for different purposes, the last part should be indented inside an **if** which allows that part to be **explicitly skipped** with a job setting.

For example,

```
if ($blocker_packages) {
 ...
}
```

Which comes from `my $blocker_packages = get_var('INSTALLATION_BLOCKED');`
Which is set as `INSTALLATION_BLOCKED=grub2`

2021-02-12 17:30 UTC, SergioAtSUSE approved these changes
LGTM

2021-02-15 07:38 UTC, czerw approved these changes

2021-02-15 07:52 UTC, pevik approved these changes

2021-02-15 07:53 UTC, merged