Enable container tests for openSUSE Maintenance
os-autoinst/os-autoinst-distri-opensuse pull request #12032
Opened 2021-02-25 16:42 UTC by pdostal

Good evening,

the aim of this pull request is to enable regular container testing on openSUSE Leap 15.1 and 15.2.
There are two ways suggested: Either creating new test suite, or including containers in `textmode`.

- Related ticket: [poo#88588](https://progress.opensuse.org/issues/88588)
- Known issues: [boo#1182507](https://bugzilla.opensuse.org/show_bug.cgi?id=1182507)
- Verification runs:
   * [openSUSE Leap 15.2 Images) > textmode@64bit](http://pdostal-server.suse.cz/tests/11132)
   * [openSUSE Leap 15.1 Images) > textmode@64bit](http://pdostal-server.suse.cz/tests/11131)

2021-03-01 15:24 UTC, Vogtinator requested changes
The approach and the change itself looks good. I don't think an additional test suite is worth it, because it would require a new installation. The additional steps here don't seem to take that long.

However, it seems like http://pdostal-server.suse.cz/tests/11132#step/rootless_podman/70 changes the directory and never goes back, which confuses later tests. Specifically consoletest_finish fails.

BTW, 15.1 is EOL, so you don't have to test that.

2021-03-31 11:02 UTC, pdostal commented
> The approach and the change itself looks good. I don't think an additional test suite is worth it, because it would require a new installation. The additional steps here don't seem to take that long.
> 
> However, it seems like http://pdostal-server.suse.cz/tests/11132#step/rootless_podman/70 changes the directory and never goes back, which confuses later tests. Specifically consoletest_finish fails.
> 
> BTW, 15.1 is EOL, so you don't have to test that.

I'm sorry, I forget about this.

The `cd` issue should be fixed and I redid the verification runs. Is it now OK for you?
Can we then merge or should someone else take a look before?

2021-03-31 11:23 UTC, Vogtinator commented
> > The approach and the change itself looks good. I don't think an additional test suite is worth it, because it would require a new installation. The additional steps here don't seem to take that long.
> > However, it seems like http://pdostal-server.suse.cz/tests/11132#step/rootless_podman/70 changes the directory and never goes back, which confuses later tests. Specifically consoletest_finish fails.
> > BTW, 15.1 is EOL, so you don't have to test that.
> 
> I'm sorry, I forget about this.

No problem - it's never too late for improvements!

> The `cd` issue should be fixed and I redid the verification runs. Is it now OK for you?

Yep! `pushd`/`popd` are technically more correct as you end up in the directory you were coming from again, but it shouldn't make a practical difference.

> Can we then merge or should someone else take a look before?

It looks good to me, but AFAICT this makes it part of the `textmode` jobs unconditionally. Where there is already a separate job for containers (like `jeos-containers` or `extra_tests_textmode_containers`), it would duplicate those test runs without increasing coverage.

Ideally this would only run in textmode for maintenance tests, but I don't see any way to do that currently.

2021-03-31 15:54 UTC, pdostal commented
> Ideally this would only run in textmode for maintenance tests, but I don't see any way to do that currently.

What about `load_extra_tests_docker()   unless (!is_released || is_desktop);`? Look at `lib/version_utils.pm`:

```
sub is_released {
    return get_var('FLAVOR') =~ /Incidents/ || get_var('FLAVOR') =~ /Updates/;
}
```

2021-04-01 13:17 UTC, Vogtinator commented
> > Ideally this would only run in textmode for maintenance tests, but I don't see any way to do that currently.
> 
> What about `load_extra_tests_docker() unless (!is_released || is_desktop);`? Look at `lib/version_utils.pm`:
> 
> ```
> sub is_released {
>     return get_var('FLAVOR') =~ /Incidents/ || get_var('FLAVOR') =~ /Updates/;
> }
> ```

Sounds good!

2021-04-07 13:38 UTC, Vogtinator approved these changes

2021-04-07 13:38 UTC, merged