Fix mutt test by installing packages unconditionally
os-autoinst/os-autoinst-distri-opensuse pull request #12073
Opened 2021-03-04 18:04 UTC by baierjan

- Related ticket: https://progress.opensuse.org/issues/89260
- Verification runs:
    - Leap 15.3: https://openqa.opensuse.org/tests/1655524
    - TW: https://openqa.opensuse.org/tests/1656118
    - SLE 12 SP5: https://openqa.suse.de/tests/5599979
    - SLE 12 SP5: https://openqa.suse.de/tests/5599980
    - SLE 15 SP2: https://openqa.suse.de/tests/5599981
    - SLE 15 SP3: https://openqa.suse.de/tests/5599978

2021-03-04 18:59 UTC, okurz requested changes
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [pr-last](http://github.com/okurz/scripts/tree/master/pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2021-03-04 20:18 UTC, baierjan commented
Ah, forgot to push the changed commit to this branch as well. Thanks for the tip for the cli command. I assume the second link should be [git-pr-last](https://github.com/okurz/scripts/blob/master/git-pr-last).

2021-03-05 10:16 UTC, okurz commented
> Ah, forgot to push the changed commit to this branch as well. Thanks for the tip for the cli command. I assume the second link should be [git-pr-last](https://github.com/okurz/scripts/blob/master/git-pr-last?rgh-link-date=2021-03-04T20%3A18%3A58Z).

thanks. I will update my github saved reply :D

2021-03-05 10:17 UTC, okurz approved these changes

2021-03-19 00:19 UTC, merged