containers: minor improvements to allow_selected_insecure_registries
os-autoinst/os-autoinst-distri-opensuse pull request #12121
Opened 2021-03-11 13:38 UTC by asmorodskyi

1. Remove creation of /etc/docker folder because actually we would like to fail in such cases
2. Make more clear error message in case unexpected runtime selected
3. Use handy function instead of direct call for sed

2021-03-11 13:45 UTC, asmorodskyi commented
@Vogtinator  can you advice me which jobs I should clone from o3 to make sure that I haven't broke anything there ?

2021-03-11 13:46 UTC, asmorodskyi commented
containers_basic from osd - http://autobot.qa.suse.de/tests/2235

2021-03-11 13:50 UTC, Vogtinator commented
> @Vogtinator can you advice me which jobs I should clone from o3 to make sure that I haven't broke anything there ?

15.2 jeos-containers: https://openqa.opensuse.org/tests/1662177
TW extra_tests_textmode_containers: https://openqa.opensuse.org/tests/1663034
MicroOS staging: https://openqa.opensuse.org/tests/1664002

That should cover most uses

2021-03-11 14:14 UTC, pdostal approved these changes
I like the `file_content_replace` 🚀 thank you Anton!

2021-03-11 14:33 UTC, asmorodskyi commented
> > @Vogtinator can you advice me which jobs I should clone from o3 to make sure that I haven't broke anything there ?
> 
> 15.2 jeos-containers: https://openqa.opensuse.org/tests/1662177
> TW extra_tests_textmode_containers: https://openqa.opensuse.org/tests/1663034
> MicroOS staging: https://openqa.opensuse.org/tests/1664002
> 
> That should cover most uses

http://autobot.qa.suse.de/tests/2236 - for 15.2 jeos-containers
http://autobot.qa.suse.de/tests/2237 - for TW extra_tests_textmode_containers

2021-03-11 14:50 UTC, asmorodskyi commented
> containers_basic from osd - http://autobot.qa.suse.de/tests/2235

this one failed in docker module with unrelated reason but I decided to re-run it anyway http://autobot.qa.suse.de/tests/2240

2021-03-11 15:03 UTC, asmorodskyi commented
> > @Vogtinator can you advice me which jobs I should clone from o3 to make sure that I haven't broke anything there ?
> 
> 15.2 jeos-containers: https://openqa.opensuse.org/tests/1662177
> TW extra_tests_textmode_containers: https://openqa.opensuse.org/tests/1663034
> MicroOS staging: https://openqa.opensuse.org/tests/1664002
> 
> That should cover most uses

http://autobot.qa.suse.de/tests/2241 - for MicroOS staging

2021-03-11 15:16 UTC, b10n1k approved these changes
+1

2021-03-12 12:58 UTC, Vogtinator requested changes
Nitpick, looks good otherwise

2021-03-12 12:58 UTC, Vogtinator commented on lib/containers/common.pm
> +        die "Not supported runtime - " . $runtime;
```suggestion
        die "Unsupported runtime - " . $runtime;
```

2021-03-12 13:28 UTC, asmorodskyi commented on lib/containers/common.pm
> +        die "Not supported runtime - " . $runtime;
done

2021-03-12 13:32 UTC, Vogtinator approved these changes

2021-03-12 13:54 UTC, merged