containers: remove duplicated function call
os-autoinst/os-autoinst-distri-opensuse pull request #12184
Opened 2021-03-19 12:00 UTC by asmorodskyi

2021-03-19 12:25 UTC, Vogtinator requested changes
AFAICT it does something different though.

`docker_image` tests the base image directly, while the call you remove here test the derived image built by the test earlier.

2021-03-19 23:08 UTC, pdostal requested changes
I've the same objection as @Vogtinator.

2021-03-21 10:15 UTC, ggkioulis requested changes

2021-03-21 10:15 UTC, ggkioulis commented on lib/containers/container_images.pm
> -    test_opensuse_based_image(image => $derived_image, runtime => $runtime);
We need this line to test the image that was created with zypper docker

2021-03-29 08:02 UTC, asmorodskyi commented
agree . sorry haven't realized this myself

2021-03-29 08:02 UTC, closed without merging