btrfsmaintenance: Capture output to help debugging
os-autoinst/os-autoinst-distri-opensuse pull request #12360
Opened 2021-04-21 07:40 UTC by foursixnine

When a job fails due to btrfs maintenance service being in a certain
unexpected state, it is difficult to know what happened without looking
at the data returned by assert_scrip_run, switching to script output
helps a bit more in this case

See: https://openqa.suse.de/tests/5846464

2021-04-22 09:56 UTC, okurz requested changes
I don't understand. What *is* the problem with looking at the data returned by assert_script_run, or more like: Look at the text output. Or is this a problem with the serial terminal approach? If that is the case maybe we should work to improve the feedback from that instead of changing all test modules?

2021-04-23 09:46 UTC, foursixnine commented
> I don't understand. What _is_ the problem with looking at the data returned by assert_script_run, or more like: Look at the text output. Or is this a problem with the serial terminal approach? If that is the case maybe we should work to improve the feedback from that instead of changing all test modules?

The PR is still in draft for a reason. Long story short, I want to figure out what's going on. Stop making assumptions :)

2021-04-24 10:53 UTC, okurz commented
> The PR is still in draft for a reason. Long story short, I want to figure out what's going on. Stop making assumptions :)

Sorry, would not know how else to review if I am not allowed to make assumptions.

2021-04-24 10:53 UTC, okurz commented
even for a draft I would assume you are asking for comments, otherwise you would not create a PR, right?

2021-04-27 14:31 UTC, foursixnine commented
> even for a draft I would assume you are asking for comments, otherwise you would not create a PR, right?

No. I would still create the PR because I want to trigger a job and I can't be bothered to use CASEDIR

2021-04-27 16:03 UTC, okurz commented
You can also use openqa-clone-custom-git-refspec also with any branch in any repo

2021-04-27 16:30 UTC, foursixnine commented
Correct, I still prefer to open a pr :)

2021-04-27 18:15 UTC, okurz commented
¯\_(ツ)_/¯

2021-07-26 14:49 UTC, closed without merging