Better timeout and UNKNOWN state handling
os-autoinst/os-autoinst-distri-opensuse pull request #12585
Opened 2021-05-24 04:11 UTC by waynechen55

* **Extend** script_run timeout to suit OSD environment. [A testsuite](https://openqa.suse.de/tests/6091356#step/uefi_guest_installation/345) already failed because of this.
* **After** thinking twice, it would be better to also do collect_guest_installation_logs_via_ssh for guest in UNKNOWN state.
* **Verification run:**
  * [Verification run](10.67.129.106/tests/1288)

2021-05-24 06:03 UTC, okurz requested changes
The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

And typo "namp"

2021-05-24 06:05 UTC, waynechen55 commented
> The commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

Already added. @okurz

2021-05-24 06:07 UTC, okurz approved these changes

2021-05-24 06:20 UTC, waynechen55 commented
@alice-suse @Julie-CAO @guoxuguang @nanzhang2020

2021-05-24 10:04 UTC, Julie-CAO commented
How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.

2021-05-24 11:10 UTC, waynechen55 commented
> How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.

With this change, I think it should around 80s ~ 90s.

2021-05-24 11:57 UTC, Julie-CAO commented
> > How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.
> 
> With this change, I think it should be around 80-85s. The worst case, namely without this change, it should be around 400s.

then how do we set timeout 3 minutes based on this change? 10 minutes(if I get it correctly) timeout is a little long.

2021-05-24 12:03 UTC, waynechen55 commented
> > > How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.
> > 
> > 
> > With this change, I think it should be around 80-85s. The worst case, namely without this change, it should be around 400s.
> 
> then how do we set timeout 3 minutes based on this change? 10 minutes(if I get it correctly) timeout is a little long.

What do you suggest ? I just want to give it more tolerance to cover even the most worst case to let it run.

2021-05-24 12:07 UTC, waynechen55 commented
> > > How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.
> > 
> > 
> > With this change, I think it should be around 80-85s. The worst case, namely without this change, it should be around 400s.
> 
> then how do we set timeout 3 minutes based on this change? 10 minutes(if I get it correctly) timeout is a little long.

I just want to cover the most worst case to let it run. If it can finish on time, then 10m makes no difference to 3m I think. Why do you insist on 3m ?

2021-05-24 12:09 UTC, Julie-CAO commented
> > > > How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.
> > > 
> > > 
> > > With this change, I think it should be around 80-85s. The worst case, namely without this change, it should be around 400s.
> > 
> > 
> > then how do we set timeout 3 minutes based on this change? 10 minutes(if I get it correctly) timeout is a little long.
> 
> I just want to cover the most worst case to let it run. If it can finish on time, then 10m makes no difference to 3m I think. Why do you insist on 3m ?

oh, I am just afraid of meaningless waiting in case of stuck. If it doesn't lead to such consequences, that's OK.

2021-05-24 13:02 UTC, waynechen55 commented
> > > > > How long does it usually take to collect single_subnet_scan_results in OSD? for the eng subnet.
> > > > 
> > > > 
> > > > With this change, I think it should be around 80-85s. The worst case, namely without this change, it should be around 400s.
> > > 
> > > 
> > > then how do we set timeout 3 minutes based on this change? 10 minutes(if I get it correctly) timeout is a little long.
> > 
> > 
> > I just want to cover the most worst case to let it run. If it can finish on time, then 10m makes no difference to 3m I think. Why do you insist on 3m ?
> 
> oh, I am just afraid of meaningless waiting in case of stuck. If it doesn't lead to such consequences, that's OK.

80-85s is the best case I think. It can cost more than that judging by a real run which took 240s. So I think 600 / get_var('TIMEOUT_SCALE', 1) is reasonable and enough to be tolerant.

2021-05-25 09:09 UTC, waynechen55 commented
@alice-suse @Julie-CAO @guoxuguang @nanzhang2020

2021-05-26 06:10 UTC, alice-suse commented
LGTM

2021-05-26 06:10 UTC, merged