Improve stability of ssh tunnel tests
os-autoinst/os-autoinst-distri-opensuse pull request #12633
Opened 2021-06-01 07:28 UTC by grisu48

Fixes occasional test failures due to flanky ssh tunnel connections when
setting up a public cloud instance.

- Related test issue: https://openqa.suse.de/tests/6143117#step/ssh_interactive_start/16
- Verification run: TBD

2021-06-01 09:58 UTC, asmorodskyi requested changes
I would like to talk about this PR

2021-06-01 11:59 UTC, asmorodskyi approved these changes

2021-06-01 11:59 UTC, merged

2021-06-09 13:37 UTC, okurz commented
Wouldn't it be the logical consequence to use `script_retry` *everywhere* instead of `assert_script_run` unless a true serial terminal is used?

2021-06-09 15:24 UTC, grisu48 commented
> Wouldn't it be the logical consequence to use `script_retry` _everywhere_ instead of `assert_script_run` unless a true serial terminal is used?

Since we encounter most of the issues only in the setup phase, that might be too much.

I think here in terms of a "heat map". The ssh connection CAN fail at any time during the whole scenario, but it is rarely happening. There are some volatile phases though, like the instantiation and when doing a instance reboot, with an increased amount of ssh-connection related failures. In those "hot spots" IMHO it makes sense to apply `script_retry`, while outside it might be overkill to catch the remaining one or two "once in a while" failures.

2021-06-09 17:13 UTC, okurz commented
Why does it fail at all then? Even "once in a while" failures should not be accepted

2021-06-10 07:34 UTC, asmorodskyi commented
> Why does it fail at all then? Even "once in a while" failures should not be accepted

keep in mind that we are running **tests** not some prod code , so I tend to disagree here this code expected to fail . `script_retry` might hide some potential bugs . Of course in ideal world automation suppose to be able to distinguish between unrelated "technical failures" and bugs but blindly retrying is not an option either

2021-06-10 08:09 UTC, okurz commented
@asmorodskyi does that mean you are against the PR because the retry can hide errors?

2021-06-10 08:32 UTC, asmorodskyi commented
> @asmorodskyi does that mean you are against the PR because the retry can hide errors?

I am not against this PR ( I merged it ) but I am against your idea to replace  `assert_script_run`'s **everywhere** with `script_retry`.

2021-06-10 11:59 UTC, okurz commented
> > @asmorodskyi does that mean you are against the PR because the retry can hide errors?
> 
> I am not against this PR ( I merged it ) but I am against your idea to replace `assert_script_run`'s **everywhere** with `script_retry`.

sorry if it was not obvious that this was sarcastic. Because of course I do not want to replace all `assert_script_run` with `script_retry`. But merely that the choice between `assert_script_run` and `script_retry` is not obvious and especially unexperienced test writers will think "my test failed from time to time, I don't understand it, maybe I will just use `script_retry`" which then leads to more and more problems. Similar as when people call all commands as root because that apparently "just works" or use `kill -9` always because "normal kill does not always work"

2021-06-10 12:45 UTC, foursixnine commented
> sorry if it was not obvious that this was sarcastic. 

Maybe let's not be sarcastic during reviews? :)

2021-06-10 16:47 UTC, okurz commented
Being 100% serious is no fun though

2021-06-11 07:57 UTC, asmorodskyi commented
> > > @asmorodskyi does that mean you are against the PR because the retry can hide errors?
> > 
> > 
> > I am not against this PR ( I merged it ) but I am against your idea to replace `assert_script_run`'s **everywhere** with `script_retry`.
> 
> sorry if it was not obvious that this was sarcastic. Because of course I do not want to replace all `assert_script_run` with `script_retry`. But merely that the choice between `assert_script_run` and `script_retry` is not obvious and especially unexperienced test writers will think "my test failed from time to time, I don't understand it, maybe I will just use `script_retry`" which then leads to more and more problems. Similar as when people call all commands as root because that apparently "just works" or use `kill -9` always because "normal kill does not always work"

yeah I got you seriously :) but looks like your joke end up as something serious - #12689 :))))

2021-06-11 08:08 UTC, grisu48 commented
> yeah I got you seriously :) but looks like your joke end up as something serious - #12689 :))))

Note to my future self in the (hopefully not occuring) case I need to go back here at some point: This fix was reverted because it didn't had the intended effect. The root cause lies probably in the fifo, which gets established earlier.