Improve test stability in patch_and_reboot test module
os-autoinst/os-autoinst-distri-opensuse pull request #12672
Opened 2021-06-08 23:38 UTC by pdostal

As the system reboots we wait for the SSH being available. But sometimes the SSH appears and then disappears for a while before being stable.

- Verification run: [sle-15-SP3-EC2-ARM-Updates](http://pdostal-server.suse.cz/tests/11981)

2021-06-09 08:46 UTC, grisu48 commented
Related ticket: https://progress.opensuse.org/issues/93695

2021-06-09 08:48 UTC, grisu48 approved these changes
LGTM! :rocket:

2021-06-09 08:49 UTC, grisu48 commented
Could you please also schedule a x86_64 test run for a non-AWS CSP? The output of `cloud-init` might be different there, also if I don't believe so.

2021-06-09 08:55 UTC, pdostal commented
> Could you please also schedule a x86_64 test run for a non-AWS CSP? The output of `cloud-init` might be different there, also if I don't believe so.

Yes, I was thinking the same way :)

2021-06-09 10:08 UTC, asmorodskyi commented
> > Could you please also schedule a x86_64 test run for a non-AWS CSP? The output of `cloud-init` might be different there, also if I don't believe so.
> 
> Yes, I was thinking the same way :) Please don't merge this yet.

let's be strict with this - in case you feel PR is not ready please put WIP into subject or convert it into draft

2021-06-09 10:10 UTC, asmorodskyi requested changes
I think it is duplicating of already existing logic https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/lib/publiccloud/instance.pm#L174 . please simply call this function here

2021-06-10 11:37 UTC, pdostal commented
Verification runs updated. Sorry, I did this yesterday but forget to commit.

2021-06-10 13:36 UTC, asmorodskyi commented
I am bit confused . From one side I see that you put thumbs up on my suggestion to re-use ` wait_for_guestregister` function and you asked for review again but on other side I see that actually you haven't actually applied my suggestion and still having initial approach.

2021-06-10 13:49 UTC, pdostal commented
> I am bit confused . From one side I see that you put thumbs up on my suggestion to re-use ` wait_for_guestregister` function and you asked for review again but on other side I see that actually you haven't actually applied my suggestion and still having initial approach.

Sorry, didn't get the function exactly but I did change my approach and implemented it in `wait_for_ssh` function.
Unfortunately we cannot use `wait_for_guestregister` as those errors happen on BYOS as well as on on demand images.

2021-06-10 14:52 UTC, asmorodskyi approved these changes
LGTM

2021-06-10 14:52 UTC, merged