containers: add zypper -n key to work properly in pipeline
os-autoinst/os-autoinst-distri-opensuse pull request #12838
Opened 2021-07-02 10:44 UTC by asmorodskyi

Based on this output https://openqa.suse.de/tests/6363986/logfile?filename=serial_terminal.txt : 

```
podman run --name refreshed registry.suse.com/suse/sle15:15.1 sh -c 'zypper -v ref | grep "All repositories have been refreshed"'; echo 7SuKZ-$?-
Cannot read input: bad stream or EOF.
If you run zypper without a terminal, use '--non-interactive' global
option to make zypper use default answers to prompts.
Repository 'SLE-Product-SLES15-SP1-Updates for sle-15-x86_64' is invalid.
[container-suseconnect-zypp:SLE-Product-SLES15-SP1-Updates|https://updates.suse.com/SUSE/Updates/SLE-Product-SLES/15-SP1/x86_64/update/?cnay613_F446IPkZfTNwx7CCsQTr34758vAy8lt5xF6J0DNTMZuNYX50cNO31KBsf9Nm-62XVwyRFYkyqV_1FnWPRNGJzHVqY4_uzaWCUxwEE2G8EcvC1ZvaLCk6f3AduFgOJuwGWD8aRRweep5mscc] Valid metadata not found at specified URL
History:
 - Cannot read input. Bad stream or EOF.
 - Can't provide /repodata/repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'SLE-Product-SLES15-SP1-Updates for sle-15-x86_64' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

VR : http://autobot.qa.suse.de/tests/2497#live

2021-07-02 12:00 UTC, jlausuch requested changes
VR failing
```
# podman run --name refreshed registry.suse.com/suse/sles12sp3 sh -c 'zypper -nv ref | grep \"All repositories have been refreshed\"'; echo X1~Jz-$?-
grep: repositories: No such file or directory
grep: have: No such file or directory
grep: been: No such file or directory
grep: refreshed": No such file or directory
```

2021-07-02 12:13 UTC, b10n1k commented
i dont get how these changes are related to the failure. Something went wrong. How the interactive_mode solves the problem here?

2021-07-02 12:23 UTC, b10n1k requested changes
Can i propose to close this and open a poo in case that you think that this is a test problem? Nevertheless seems the the test passes later on. So maybe a network issue??

2021-07-02 12:46 UTC, pdostal approved these changes
This is just nice change. I vote for merging it even if it does not solve that issue.

2021-07-02 12:53 UTC, asmorodskyi commented
> i dont get how these changes are related to the failure. Something went wrong. How the interactive_mode solves the problem here?

I am NOT trying to solve this : 
```
Repository 'SLE-Product-SLES15-SP1-Updates for sle-15-x86_64' is invalid.
[container-suseconnect-zypp:SLE-Product-SLES15-SP1-Updates|https://updates.suse.com/SUSE/Updates/SLE-Product-SLES/15-SP1/x86_64/update/?cnay613_F446IPkZfTNwx7CCsQTr34758vAy8lt5xF6J0DNTMZuNYX50cNO31KBsf9Nm-62XVwyRFYkyqV_1FnWPRNGJzHVqY4_uzaWCUxwEE2G8EcvC1ZvaLCk6f3AduFgOJuwGWD8aRRweep5mscc] Valid metadata not found at specified URL
History:
 - Cannot read input. Bad stream or EOF.
 - Can't provide /repodata/repomd.xml

Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'SLE-Product-SLES15-SP1-Updates for sle-15-x86_64' because of the above error.
Some of the repositories have not been refreshed because of an error.
```

but I am trying to solve this : 
```
Cannot read input: bad stream or EOF.
If you run zypper without a terminal, use '--non-interactive' global
option to make zypper use default answers to prompts.
```

first is really network hiccup , second is about the fact that without `-n`  zypper sending something which can not be handled in pipeline properly . At least this is how I understand this part of the message .

2021-07-02 12:56 UTC, asmorodskyi commented
> Can i propose to close this and open a poo in case that you think that this is a test problem? Nevertheless seems the the test passes later on. So maybe a network issue??

yes test is passing , but my PR is not related to the fact whether test is passing or failing I am trying to improve zypper usage based on recommendations from zypper :)

2021-07-09 15:09 UTC, asmorodskyi commented
I did a closer look into the issues , this PR is wrong . 
This error reproducible even on local machine : 
```
zypper -nv ref | grep \"All repositories have been refreshed\"'
grep: repositories: No such file or directory
grep: have: No such file or directory
grep: been: No such file or directory
grep: refreshed": No such file or directory
```

I think there is a clash between use of `-n` which designed for non-interactive usage and `-v` . I think bigger changes needed here . If we want to use `-n` we need to stop grep the output but track exit code . This PR was created because I thought that I will do BTW quick fix . it didn't workout so I am closing this PR and open a ticket instead for further investigation https://progress.opensuse.org/issues/95311

2021-07-09 15:09 UTC, closed without merging