publiccloud: propagate retval into LTP_KNOWN_ISSUES flow
os-autoinst/os-autoinst-distri-opensuse pull request #12980
Opened 2021-07-27 08:39 UTC by asmorodskyi

2021-07-27 08:49 UTC, mdoucha approved these changes
LGTM

2021-07-27 09:52 UTC, pevik approved these changes
LGTM

2021-08-10 14:23 UTC, cfconrad commented on tests/publiccloud/run_ltp.pm
>              my $entry = find_whitelist_entry($env, $suite, $test->{test_fqn});
```suggestion
            $env->{retval} = $test->{retval};
            my $entry = find_whitelist_entry($env, $suite, $test->{test_fqn});
            next unless (defined($entry));
```

2021-08-10 14:28 UTC, cfconrad requested changes
I have the feeling this isn't read yet.

E.g. `download_whitelist();` doesn't return anything useful and we use it to decide if we wanna `process_ltp_known_issues()`.

2021-08-10 14:28 UTC, cfconrad commented on tests/publiccloud/run_ltp.pm
>              my $entry = find_whitelist_entry($env, $suite, $test->{test_fqn});
We never check if a whitelist entry exists, so from my perspective we just blindly overwrite all results?!

2021-08-13 09:05 UTC, cfconrad commented
As @asmorodskyi is on holiday, we continue with this: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13065

2021-09-16 08:58 UTC, closed without merging