Containers: schedule buildah tests only in 1 place
os-autoinst/os-autoinst-distri-opensuse pull request #13004
Opened 2021-07-30 10:34 UTC by jlausuch

For some reason we were scheduling buildah tests in
engines and tools and also in sle image on sle host.
Let's just run it in single place.

- Related ticket:  https://progress.opensuse.org/issues/95626

2021-07-30 10:36 UTC, jlausuch commented
https://openqa.suse.de/tests/overview?version=15-SP4&build=jlausuch%2Fos-autoinst-distri-opensuse%23containers_buildah_condition&distri=sle

2021-07-30 12:42 UTC, pdostal requested changes
I don't understand where will we be running podman after this PR.

2021-07-30 12:42 UTC, pdostal commented on schedule/containers/engines_and_tools_docker.yaml
> -  supported:
The `supported` conditional schedule is fully remove but still present under schedule.

2021-07-30 12:50 UTC, jlausuch commented
> I don't understand where will we be running podman after this PR.

it is still [here](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/schedule/containers/sle_image_on_sle_host_podman.yaml#L15) ... there was some mess after the refactor we did with the yaml schedules.. so podman/docker will be run in engines_and_tools and podman/docker_image in sle_image_on_... together with buildah_podman/docker

2021-07-30 12:58 UTC, pdostal approved these changes
Thank you @jlausuch 🎉

2021-07-30 13:37 UTC, jlausuch commented
Let's first decide https://progress.opensuse.org/issues/96383

2021-08-03 15:36 UTC, b10n1k requested changes
if i am not wrong this commit removes buildah from the host testing. i thought we want the opposite. 

https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13021

2021-08-04 16:22 UTC, jlausuch commented
> if i am not wrong this commit removes buildah from the host testing. i thought we want the opposite.
> 
> #13021

indeed, this was done before discussing. Closing it.

2021-08-04 16:22 UTC, closed without merging