Move buildah and validate_btrfs on host related tests
os-autoinst/os-autoinst-distri-opensuse pull request #13021
Opened 2021-08-03 15:31 UTC by b10n1k

Find and reassign some modules to the correct group and run them only in a single place.

The reason they removed from image testing jobs are:

- buildah is unlikely to find any problem on the images other than podman will find.
this is because it used by podman underneath. Buildah is more likely to find bugs against
the sut rather the images.

- validate_btrfs tests the docker storage fs feature which likely belongs to the host tests as well.

- Related ticket: https://progress.opensuse.org/issues/96383
- Verification run: tbd

2021-08-04 09:48 UTC, pdostal requested changes

2021-08-04 09:48 UTC, pdostal commented on schedule/containers/sle_image_on_sle_host_docker.yaml
> -  - containers/container_diff
The `container_diff` should be in image tests as it probes particular image.

2021-08-04 09:49 UTC, pdostal commented on schedule/containers/sle_image_on_sle_host_docker.yaml
> -  - containers/container_diff
That is all from my side, I agree with the rest. No new verification run needed either :smile:

2021-08-04 10:02 UTC, pdostal approved these changes
Thank you :rocket:

2021-08-05 17:04 UTC, jlausuch approved these changes
LGTM

2021-08-05 17:04 UTC, merged