Don't operate firewall when system role is Common Criteria
os-autoinst/os-autoinst-distri-opensuse pull request #13625
Opened 2021-11-08 03:57 UTC by Amrysliu

When system role is Common Criteria, the firewall is not installed in
the system by default. Then it will report `Unit file firewalld.service
does not exist` when disabling it in setup_multimachine.pm.

- Related ticket:  https://progress.opensuse.org/issues/102011
- Needles: N/A
- Verification run:

2021-11-09 12:29 UTC, mdoucha commented
It might be better to check for firewall presence using `systemctl list-unit-files --all $firewall*` instead of hardcoding SYSTEM_ROLE condition. Note that the asterisk at the end is required, otherwise it won't find anything.

2021-11-09 12:31 UTC, mdoucha requested changes
It might be better to check for firewall presence using `systemctl list-unit-files --all $firewall*` instead of hardcoding SYSTEM_ROLE condition. Note that the asterisk at the end is required, otherwise it won't find anything.

2021-11-09 13:09 UTC, Amrysliu commented
> It might be better to check for firewall presence using `systemctl list-unit-files --all $firewall*` instead of hardcoding SYSTEM_ROLE condition. Note that the asterisk at the end is required, otherwise it won't find anything.

Thanks. Modified.

2021-11-09 13:44 UTC, mdoucha commented
1. It'd be better to create a reusable library function for this
2. You need to pass the contents of `$self->firewall`, not the plain string "firewall".

2021-11-10 06:53 UTC, Amrysliu commented
> 1. It'd be better to create a reusable library function for this
> 2. You need to pass the contents of `$self->firewall`, not the plain string "firewall".

Good suggestions.  Thanks.

2021-11-10 09:19 UTC, mdoucha commented
The library function should go into lib/Utils/Systemd.pm

2021-11-10 09:54 UTC, mdoucha approved these changes
LGTM

2021-11-10 10:02 UTC, Amrysliu commented
> LGTM

Thanks for your help and reviewing.

2021-11-11 02:26 UTC, rfan1 approved these changes
LGTM

2021-11-11 02:55 UTC, tinawang123 approved these changes
LGTM

2021-11-11 05:59 UTC, merged

2021-11-11 06:03 UTC, lilyeyes reviewed
LGTM

2021-11-11 06:05 UTC, jouyingbin commented
LGTM

2021-11-11 06:09 UTC, jouyingbin reviewed
LGTM