Update EXTRABOOTPARAMS handler
os-autoinst/os-autoinst-distri-opensuse pull request #13647
Opened 2021-11-09 11:13 UTC by mloviska

Starting with grub 2.06 the config layout is similar in TW, Leap15.4
and sle15sp4. This requires an update of EXTRABOOTPARAMS handler.

* Issues:
  * [15.4](http://kepler.suse.cz/tests/8842#step/bootloader_uefi/5)
  * [sle15sp4](http://kepler.suse.cz/tests/8845)

#### VRs:

* [opensuse-15.4-JeOS-for-kvm-and-xen-x86_64-Build4.9-kernel_parameters@64bit_virtio-2G](http://kepler.suse.cz/tests/8857#step/check_kernel_params/2)
* [sle-15-SP4-JeOS-for-kvm-and-xen-x86_64-Build1.111-kernel_parameters@uefi-virtio-vga](http://kepler.suse.cz/tests/8852#step/check_kernel_params/2)
* [opensuse-15.3-JeOS-for-kvm-and-xen-x86_64-Build9.273-kernel_parameters@uefi_virtio-2G](http://kepler.suse.cz/tests/8854#step/check_kernel_params/2)
* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64-Build20211107-kernel_parameters@64bit_virtio](http://kepler.suse.cz/tests/8855#step/check_kernel_params/2)
* [sle-15-SP3-JeOS-for-kvm-and-xen-Updates-x86_64-Build20211109-1-kernel_parameters@uefi-virtio-vga](http://kepler.suse.cz/tests/8853#step/check_kernel_params/2)
* [opensuse-15.2-JeOS-for-kvm-and-xen-x86_64-Build31.592-kernel_parameters@uefi_virtio-2G](http://kepler.suse.cz/tests/8858#step/check_kernel_params/2)
* [sle-15-SP2-JeOS-for-kvm-and-xen-Updates-x86_64-Build20211109-1-kernel_parameters@uefi-virtio-vga](http://kepler.suse.cz/tests/8851#step/check_kernel_params/2)
* [sle-12-SP5-JeOS-for-kvm-and-xen-Updates-x86_64-Build20211109-1-kernel_parameters@64bit-virtio-vga](http://kepler.suse.cz/tests/8850#step/check_kernel_params/2)

2021-11-09 11:28 UTC, jlausuch approved these changes

2021-11-09 13:05 UTC, ggardet requested changes
Could you update the comment above your changes accordingly, please? Otherwise, LGTM. (I cannot reach the VRs, though)

2021-11-09 14:35 UTC, mloviska commented
> Could you update the comment above your changes accordingly, please? Otherwise, LGTM. (I cannot reach the VRs, though)

Description updated, here are few VRs in o3

* [opensuse-Tumbleweed-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/2025020#details)
* [opensuse-15.4-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/2025023)
* [opensuse-15.3-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/2025024)
* [opensuse-15.2-JeOS-for-kvm-and-xen-x86_64](https://openqa.opensuse.org/tests/2025025)

2021-11-09 16:29 UTC, ggardet commented
> > Could you update the comment above your changes accordingly, please? Otherwise, LGTM. (I cannot reach the VRs, though)
> 
> Description updated, here are few VRs in o3

I meant update this comment `# On Leap/SLE we need to move down (grub 2.04)`
Thanks for the VR on o3.

2021-11-09 16:33 UTC, ggardet commented
It would be great to be more precise, since Leap/SLE uses grub 2.06 with SLE15-SP4+/15.4+

2021-11-09 16:37 UTC, mloviska commented
> It would be great to be more precise, since Leap/SLE uses grub 2.06 with SLE15-SP4+/15.4+

Fair point, done!

2021-11-09 16:44 UTC, ggardet commented
> > It would be great to be more precise, since Leap/SLE uses grub 2.06 with SLE15-SP4+/15.4+
> 
> Fair point, done!

If you write it this way, you should add Tumbleweed as well, since it includes grub 2.06. ;)

2021-11-09 16:53 UTC, mloviska commented
> > > It would be great to be more precise, since Leap/SLE uses grub 2.06 with SLE15-SP4+/15.4+
> > 
> > 
> > Fair point, done!
> 
> If you write it this way, you should add Tumbleweed as well, since it includes grub 2.06. ;)

Very true! :D

2021-11-10 08:11 UTC, ggardet approved these changes

2021-11-10 09:55 UTC, merged