Adjust shortcut to open "Activities" in GNOME41
os-autoinst/os-autoinst-distri-opensuse pull request #13661
Opened 2021-11-11 07:28 UTC by zhaocongjia

In GNOME41, use shortcut `alt-f1` to open "Activities" is removed.  So use shortcut `super` instead.

- Related ticket: https://progress.opensuse.org/issues/101917
- Needles: None
- Verification run: https://openqa.suse.de/tests/7647470#step/libreoffice_mainmenu_favorites/1

2021-11-15 10:37 UTC, GraceWang571 commented on tests/x11/libreoffice/libreoffice_mainmenu_favorites.pm
> +# Copyright 2016-2021 SUSE LLC
@zhaocongjia  Based on the 2nd item in https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style "Prefer to not update the copyright years in file headers as this is not required."
Could you please change the copyright year back?

2021-11-15 12:08 UTC, okurz requested changes
As already explained by @GraceWang571 

Also, what's the impact on older versions of openSUSE/SLE with older gnome versions?

2021-11-16 01:12 UTC, zhaocongjia commented
I have rebased and amended my commit.  For Oliver's question, we already use 'Super' everywhere else in the code base.

2021-11-16 08:12 UTC, okurz commented
> I have rebased and amended my commit. For Oliver's question, we already use 'Super' everywhere else in the code base.

So do you mean that this won't affect older versions because all currently supported SLE+gnome versions are ok with the "Super" key? I would appreciate according verification runs

2021-11-16 08:48 UTC, zhaocongjia commented
The evidence that `Super` worked on older releases is:

https://openqa.suse.de/tests/7676301#step/libreoffice_mainmenu_components/1

This is SLE15SP3 with GNOME 3.34, this `libreoffice_mainmenu_components` test uses `Super` and it works.
(https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/ab0901ee7f65f5d4c5886f5e8de3f1327dcb0678/tests/x11/libreoffice/libreoffice_mainmenu_components.pm#L71)

2021-11-16 08:53 UTC, okurz approved these changes
Well, but what about the oldest product still maintained where that module is called? Using https://github.com/okurz/scripts/blob/master/openqa-db_query_last_use_of_module I found for example:

```
 sle    | 15-SP2  | Desktop-DVD-Updates | qam-regression-documentation                                                                                           | x86_64 | 64bit
 sle    | 15-SP2  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_build:20211103-1                                                    | x86_64 | 64bit
 sle    | 15-SP2  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_tests:d2f3a26dd60dd74143a54e173b28e7d166ac8da7                      | x86_64 | 64bit
 sle    | 15-SP2  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_tests_and_build:d2f3a26dd60dd74143a54e173b28e7d166ac8da7+20211103-1 | x86_64 | 64bit
 sle    | 15-SP2  | Desktop-DVD-Updates | qam-regression-documentation:investigate:retry                                                                         | x86_64 | 64bit
 sle    | 15-SP3  | Desktop-DVD-Updates | qam-regression-documentation                                                                                           | x86_64 | 64bit
 sle    | 15-SP3  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_build:20211103-1                                                    | x86_64 | 64bit
 sle    | 15-SP3  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_tests:d2f3a26dd60dd74143a54e173b28e7d166ac8da7                      | x86_64 | 64bit
 sle    | 15-SP3  | Desktop-DVD-Updates | qam-regression-documentation:investigate:last_good_tests_and_build:d2f3a26dd60dd74143a54e173b28e7d166ac8da7+20211103-1 | x86_64 | 64bit
 sle    | 15-SP3  | Desktop-DVD-Updates | qam-regression-documentation:investigate:retry                                                                         | x86_64 | 64bit
 sle    | 15-SP4  | Online              | wayland-desktopapps-documentation                                                                                      | x86_64 | 64bit-virtio-vga
 sle    | 15-SP4  | Online              | wayland-desktopapps-documentation:investigate:last_good_tests:65aca837aa4deaa1021f4edca4138bcf30931ab7                 | x86_64 | 64bit-virtio-vga
 sle    | 15-SP4  | Online              | wayland-desktopapps-documentation:investigate:retry                                                                    | x86_64 | 64bit-virtio-vga
 sle    | 15-SP4  | Online              | x11-desktopapps-documentation                                                                                          | x86_64 | 64bit-2gbram
 sle    | 15-SP4  | Online              | x11-desktopapps-documentation:investigate:retry                                                                        | x86_64 | 64bit-2gbram
```

so at least 15-SP2 is also relevant. Seeing https://openqa.suse.de/tests/7687929#step/libreoffice_mainmenu_components/15 it seems like the Super key works there as well. So I can approve.

2021-11-17 01:15 UTC, GraceWang571 approved these changes
Based on the above talking, we are fine and ready to merge this PR.

2021-11-17 01:15 UTC, merged