pam: Copy template config form /usr/etc if not existing in /etc yet
os-autoinst/os-autoinst-distri-opensuse pull request #13809
Opened 2021-12-03 14:53 UTC by DimStar77

pam moved its distro config files to /usr/etc/security, with the admin being expected to modify his copies in /etc. Prepare the test to do just that

- Related ticket: 
- Needles: N/A
- Verification run: TBD

2021-12-06 09:47 UTC, foursixnine approved these changes
I guess this would be compatible with older releases

2021-12-06 10:38 UTC, DimStar77 commented
> I guess this would be compatible with older releases

should well be, as I only copy files from /usr/etc if they do not exist in /etc

2021-12-06 15:24 UTC, Vogtinator commented
The intention of the backup and restore is to keep the system unmodified after the test completed, FWICT. This way it doesn't quite achive that anymore, because the `/usr/etc/` files were copied to `/etc`. No idea whether that can be an issue in practice, probably not?

2021-12-06 15:39 UTC, Vogtinator requested changes
There's a typo.

What about just making a backup if those files exist and for restoring just delete the config file if there's no backup? That's how I handled it for openscap in 1c1eba73a0f797cef606bf8e410d36e9019079e7. No idea how the test behaves with that.

2021-12-06 15:39 UTC, Vogtinator commented on data/pam_test/pam.sh
> +    test ! -f /etc/security/access.conf && cp /usr/etc/security/access.cof /etc/security/access.conf
Typo

2021-12-07 08:22 UTC, DimStar77 commented on data/pam_test/pam.sh
> +    test ! -f /etc/security/access.conf && cp /usr/etc/security/access.cof /etc/security/access.conf
typo fixed

2021-12-07 08:25 UTC, DimStar77 commented
> The intention of the backup and restore is to keep the system unmodified after the test completed, FWICT. This way it doesn't quite achive that anymore, because the `/usr/etc/` files were copied to `/etc`. No idea whether that can be an issue in practice, probably not?

as they are 1:1 copies, the files in /etc should just take precedence over the ones in /usr/etc, but being equal, the result should be close (enough) to equal (granted, not perfect)

2021-12-08 15:03 UTC, Vogtinator approved these changes

2021-12-08 15:06 UTC, merged