installation/await_install: Bump timeout for powepc
os-autoinst/os-autoinst-distri-opensuse pull request #13885
Opened 2021-12-16 16:02 UTC by foursixnine

Installation is taking a bit longer nowdays, and while I'm not sure that it's due to network or some other issue, those extra 10 minutes should help, as most of the times... looks like await install is just shy of minutes before finishing the installation

https://openqa.suse.de/tests/7856741#step/await_install/69

See also https://progress.opensuse.org/issues/104106

2021-12-17 08:51 UTC, dzedro approved these changes

2021-12-17 08:53 UTC, okurz requested changes
s/powepc/PowerPC/ or ppc or something. The problem is https://progress.opensuse.org/issues/102882 which is really specific to one rack in a server room used by the OSD infrastructure. I suggest to use TIMEOUT_SCALE in the worker specific config, not change the test code

2021-12-17 09:14 UTC, punkioudi approved these changes
lgtm!

2021-12-17 11:25 UTC, foursixnine commented
> s/powepc/PowerPC/ or ppc or something. The problem is https://progress.opensuse.org/issues/102882 which is really specific to one rack in a server room used by the OSD infrastructure. I suggest to use TIMEOUT_SCALE in the worker specific config, not change the test code

I will still move forward, as the test normally takes 12m, and the extra timeout should cover for future problems in the network even after https://gitlab.suse.de/openqa/salt-pillars-openqa/-/merge_requests/375, or for the time it is reverted.

2021-12-20 08:45 UTC, merged

2021-12-20 12:28 UTC, okurz commented
You could have at least fixed the typo :,( I don't think it's a good style to merge despite someone requesting changes.

2021-12-20 12:36 UTC, foursixnine commented
> You could have at least fixed the typo :
Which typo? :) I hope you're seeing it now and not during your first review

2021-12-20 12:41 UTC, okurz commented
The typo I mentioned in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13885#pullrequestreview-834975929

> s/powepc/PowerPC/ or ppc or something.

Seems like you overlooked my first message. That's ok, mistakes happen. But even more so this is why I suggest to not merge despite changes requested.

2021-12-20 12:49 UTC, foursixnine commented
> The typo I mentioned in [#13885 (review)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/13885#pullrequestreview-834975929)
> 
> > s/powepc/PowerPC/ or ppc or something.
> 
> Seems like you overlooked my first message. That's ok, mistakes happen. But even more so this is why I suggest to not merge despite changes requested.

Ah, wasn't really clear what you meant, the second part of that comment diluted the possible meaning of it.

wrt merging despite changes requested, let's say that there's a calculated risk (if any) to simply waiting for a bit longer, instead of just waiting for the workaround.

git history will show how that there's a reason for that in the future, and that would be a better early warning in the future (including to check for typos before merging :).

2021-12-20 13:13 UTC, okurz commented
sure, not the end of the world :)