fix erratic behavior of setting up the network on windows
os-autoinst/os-autoinst-distri-opensuse pull request #14088
Opened 2022-01-24 11:05 UTC by bs-suse

This fix uses the windows from wsl/boot_windows as base.
Due to the issue that the network adapter is sometimes (possibly
depending on the worker setup?) named "Ethernet" and sometimes
"Ethernet 2" there is the need to first find the name and use that
to actually set up the network.
This fix implements that.
For that, powershell cmdlets are used instead of netsh.

- Related issue: https://openqa.suse.de/tests/7924149#step/windows_network_setup/5
- Needles: https://gitlab.suse.de/bschmidt/os-autoinst-needles-sles/-/commit/9dd40a700cf3c70672ce2108430ac5d916a66e8d
- Verification run: http://keks.qa.suse.de/tests/386#step/windows_network_setup/21

2022-01-24 11:19 UTC, ricardobranco777 approved these changes
LGTM. Thanks!

2022-01-24 14:08 UTC, okurz requested changes
* Please phrase the git commit message subject lines starting with a capital letter
* Squash the commits
* See inline comments

2022-01-24 14:08 UTC, okurz commented on tests/x11/remote_desktop/windows_network_setup.pm
> +# Copyright 2018-2022 SUSE LLC
please keep the old date. See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md?plain=1#L49 for this

2022-01-24 14:08 UTC, okurz commented on tests/x11/remote_desktop/windows_network_setup.pm
> +    wait_still_screen stilltime => 5, timeout => 10;
There should not be a need for a `wait_still_screen` as the subsequent `assert_screen` should already cover the waiting period with the sufficient timeout

2022-01-24 16:10 UTC, okurz commented on tests/x11/remote_desktop/windows_network_setup.pm
> +    wait_still_screen stilltime => 5, timeout => 10;
Then you might need to reconsider your needles that you use in the next call. Just think how a human tester would conduct this and we should realize we shouldn't need this command here :)

2022-01-25 07:26 UTC, okurz approved these changes

2022-01-25 08:01 UTC, merged

2022-01-25 14:52 UTC, DimStar77 commented
Is that related to the new failures on https://openqa.opensuse.org/tests/2156917#step/windows_network_setup/20 ?

2022-01-25 15:10 UTC, okurz commented
You are right. https://openqa.opensuse.org/tests/2156549#investigation very much makes it look like it. I forgot to ask for openSUSE verification. I am not that good of a reviewer for os-autoinst-distri-opensuse anymore, it seems ;) I will propose a revert.