wicked: Add test t17_ifrename
os-autoinst/os-autoinst-distri-opensuse pull request #14092
Opened 2022-01-24 14:35 UTC by cfconrad

Bug: https://bugzilla.suse.com/show_bug.cgi?id=1194392

- Verification run: http://openqa.wicked.suse.de/tests/47837

2022-01-24 18:13 UTC, jlausuch commented on tests/wicked/startandstop/sut/t17_ifrename.pm
> +#             Jose Lausuch <jalausuch@suse.com>
feel free to remove me :D 
Or just add qac ML

2022-01-26 14:21 UTC, asmorodskyi requested changes
disagree with changes related to check_logs . Don't see why we need to add flow with `$code` and `$cursor` inside check_logs function it is unrelated to function purposes

2022-01-29 16:15 UTC, cfconrad commented
The advantage is, that you actually can tell what call cause the log error as you can check logs during the testmodule and not just at the end, where you do not know what actually cause it and you need to compare timecodes or so to determine the actual root cause.

2022-02-14 22:35 UTC, cfconrad commented
any news?

2022-02-17 21:40 UTC, cfconrad commented
or suggestion, like you would add the script within 4 testmodules...

2022-02-18 13:44 UTC, asmorodskyi commented
> or suggestion, like you would add the script within 4 testmodules...

no I can not suggest anything :( so I think we have no other choice than follow your idea . sorry that I was holding it so long without good reason :(

2022-02-18 13:44 UTC, merged