Remove 'vim' out of installation console-tests
os-autoinst/os-autoinst-distri-opensuse pull request #14201
Opened 2022-02-08 12:43 UTC by Zaoliang

see https://progress.opensuse.org/issues/95724
verification:
https://openqa.opensuse.org/tests/2178941#step/vim

2022-02-08 12:45 UTC, okurz commented
@DimStar77

2022-02-08 12:46 UTC, okurz requested changes
Please explain in your git commit message how the coverage for vim is ensured if it's not included in the installation tests anymore. Do staging tests still execute the vim test module?

2022-02-08 15:21 UTC, Zaoliang commented
the idea is about put vim into extra_test_misc. vim should not be tested within installation in general. And I don't know why for staging this module is required. 
At moment isotovideo failed, investigation...

2022-02-08 15:28 UTC, okurz commented
> the idea is about put vim into extra_test_misc. vim should not be tested within installation in general.

I know what the ticket says but the git commit messages should be self-contained to be able to understand the motivation of a change.

> And I don't know why for staging this module is required

Well, if you don't know then don't change it. You change the schedule so it could be that the staging schedule does not include the module anymore.

2022-02-09 07:57 UTC, DimStar77 commented
> the idea is about put vim into extra_test_misc. vim should not be tested within installation in general. And I don't know why for staging this module is required. At moment isotovideo failed, investigation...

Staging, in general, is 'to ensure things do never break'; this implies that vim needs to be tested in staging; otherwise, we can't see side-effects impacting vim until they are checked in into a product, which in turn needlessly delays product/snapshot releases

2022-02-09 09:49 UTC, Martchus commented
Note that tests are likely failing because the test module is still referenced here: https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/651f604045f15a4eb4d42964a921e733bca28b7b/t/data/test_schedule.out#L38

2022-02-09 10:00 UTC, okurz commented
> Note that tests are likely failing because the test module is still referenced here:
> 
> https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/651f604045f15a4eb4d42964a921e733bca28b7b/t/data/test_schedule.out#L38

IMHO as it should be. And that's also the discussion regarding staging tests

2022-02-10 07:45 UTC, Zaoliang commented
will find another way to handle this issue.

2022-02-10 07:45 UTC, closed without merging