To make sure the firefox menu can show up
os-autoinst/os-autoinst-distri-opensuse pull request #14436
Opened 2022-03-08 03:38 UTC by tinawang123

To make sure the firefox menu can show up

- Related ticket: https://progress.opensuse.org/issues/103533
- Verification run: 
opensuse:https://openqa.opensuse.org/t2232952
https://openqa.opensuse.org/t2232953
https://openqa.opensuse.org/t2232954
https://openqa.opensuse.org/t2232955
https://openqa.opensuse.org/t2232956
https://openqa.opensuse.org/t2232957
https://openqa.opensuse.org/t2232958
https://openqa.opensuse.org/t2232959
https://openqa.opensuse.org/t2232960
https://openqa.opensuse.org/t2232961

2022-03-09 01:47 UTC, lemon-suse approved these changes

2022-03-09 05:47 UTC, okurz requested changes
In your git commit message you repeat the same sentence twice. 
Instead the commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.

I suggest to collect the current failure ratio and come up with a value in percent on a big enough data set. Then prove that with your fix the fail ratio is significantly lower

2022-03-10 02:39 UTC, tinawang123 commented
> In your git commit message you repeat the same sentence twice. Instead the commit message could have a bit more details, e.g. what issue is fixed, why this needs to change, to which versions of which product it applies, link to a bug or a fate entry, the choices you made, etc. Also see https://commit.style/ or http://chris.beams.io/posts/git-commit/ as a helpful guide how to write good commit messages.
> 
> I suggest to collect the current failure ratio and come up with a value in percent on a big enough data set. Then prove that with your fix the fail ratio is significantly lower

Updated.

2022-03-10 06:43 UTC, okurz commented
ok, this looks promising already. I just updated https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation so you could use the proposed solution there to trigger jobs in special builds so instead of referencing individual jobs you could reference a test overview page showing the complete results so that we could easily see the fail-ratio. Also I suggest to use http://open.qa/docs/#_defining_a_custom_test_schedule_or_custom_test_modules so for example you could exclude some module or use a custom schedule. I guess the most minimum case could be TESTS=tests/boot/boot_to_desktop,tests/x11/firefox

2022-03-14 01:25 UTC, tinawang123 commented
> ok, this looks promising already. I just updated https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation so you could use the proposed solution there to trigger jobs in special builds so instead of referencing individual jobs you could reference a test overview page showing the complete results so that we could easily see the fail-ratio. Also I suggest to use http://open.qa/docs/#_defining_a_custom_test_schedule_or_custom_test_modules so for example you could exclude some module or use a custom schedule. I guess the most minimum case could be TESTS=tests/boot/boot_to_desktop,tests/x11/firefox

Run 100 times, https://openqa.opensuse.org/tests/overview?build=poo103533_investigation&version=Tumbleweed&distri=opensuse
All of them about firefox can pass

2022-03-14 07:40 UTC, BillAnastasiadis commented
Thank you @tinawang123 for this contribution. I think if you change the commit message title from "**To make sure the firefox menu can show up **" to **"Make sure the firefox menu can show up "**, the commit would be ready to merge.

2022-03-14 08:06 UTC, tinawang123 commented
> Thank you @tinawang123 for this contribution. I think if you change the commit message title from "**To make sure the firefox menu can show up "** to **"Make sure the firefox menu can show up "**, the commit would be ready to merge.

Thanks , changed

2022-03-14 08:39 UTC, BillAnastasiadis commented
Thank you! Could you please also change it in the git message along with the github one? Meaning, `git commit --amend` and then changing the commit message title.

2022-03-14 09:16 UTC, tinawang123 commented
> Thank you! Could you please also change it in the git message along with the github one? Meaning, `git commit --amend` and then changing the commit message title.

Updated

2022-03-14 09:41 UTC, BillAnastasiadis commented
Thanks @tinawang123!
@okurz do you think we can give this a go?

2022-03-15 09:04 UTC, tinawang123 commented
@okurz any update?

2022-03-15 10:29 UTC, okurz commented
> > ok, this looks promising already. I just updated https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation so you could use the proposed solution there to trigger jobs in special builds so instead of referencing individual jobs you could reference a test overview page showing the complete results so that we could easily see the fail-ratio. Also I suggest to use http://open.qa/docs/#_defining_a_custom_test_schedule_or_custom_test_modules so for example you could exclude some module or use a custom schedule. I guess the most minimum case could be TESTS=tests/boot/boot_to_desktop,tests/x11/firefox
> 
> Run 100 times, https://openqa.opensuse.org/tests/overview?build=poo103533_investigation&version=Tumbleweed&distri=opensuse All of them about firefox can pass

That's great. I think I still need to be more clear. A proper scientific approach to prove that the hypothesis is correct does need the fail ratio from before though. It is great to see that firefox can pass in 100/100 cases, meaning a fail ratio of 0.00%+-0.01% but if the fail ratio in before was below 0.01% percent this still would not be an improvement. I suggest to include such information in the git commit message now.

2022-03-16 03:31 UTC, tinawang123 commented
> > > ok, this looks promising already. I just updated https://progress.opensuse.org/projects/openqatests/wiki/Wiki#Statistical-investigation so you could use the proposed solution there to trigger jobs in special builds so instead of referencing individual jobs you could reference a test overview page showing the complete results so that we could easily see the fail-ratio. Also I suggest to use http://open.qa/docs/#_defining_a_custom_test_schedule_or_custom_test_modules so for example you could exclude some module or use a custom schedule. I guess the most minimum case could be TESTS=tests/boot/boot_to_desktop,tests/x11/firefox
> > 
> > 
> > Run 100 times, https://openqa.opensuse.org/tests/overview?build=poo103533_investigation&version=Tumbleweed&distri=opensuse All of them about firefox can pass
> 
> That's great. I think I still need to be more clear. A proper scientific approach to prove that the hypothesis is correct does need the fail ratio from before though. It is great to see that firefox can pass in 100/100 cases, meaning a fail ratio of 0.00%+-0.01% but if the fail ratio in before was below 0.01% percent this still would not be an improvement. I suggest to include such information in the git commit message now.

Checked https://openqa.opensuse.org/tests/2245717#next_previous. From firefox first failed case, there are 2/19 test cases failed.

2022-03-16 07:06 UTC, okurz commented
> Checked https://openqa.opensuse.org/tests/2245717#next_previous. From firefox first failed case, there are 2/19 test cases failed.

ok, can you include that information about the current state and the results from your statistics after your changes in the git commit message?

2022-03-16 07:23 UTC, tinawang123 commented
> > Checked https://openqa.opensuse.org/tests/2245717#next_previous. From firefox first failed case, there are 2/19 test cases failed.
> 
> ok, can you include that information about the current state and the results from your statistics after your changes in the git commit message?

Updated git commit information

2022-03-17 06:31 UTC, merged