klp: Remove livepatch git revision check
os-autoinst/os-autoinst-distri-opensuse pull request #14701
Opened 2022-04-11 16:17 UTC by pevik

livepatch git revision check was removed from uname output, thus remove the check from test. Check for git-hash/(lp|kGraft) was kept.

Link: bsc#1196281

Verification run:
- http://quasar.suse.cz/tests/8925 (SLES)
NOTE: openSUSE does not use this test

2022-04-11 16:18 UTC, pevik commented
@nicstange can you please review?
@mdoucha @czerw FYI

2022-04-12 10:43 UTC, mdoucha commented
The git revision still exists in SLE-15SP3 and earlier. I've asked in the BSC whether that's going to change. If this is just a 15-SP4 thing, then we should make the git revision check conditional instead of removing it completely.

2022-04-12 10:45 UTC, mdoucha commented
Please mark this as `WIP:` until we get a reply and use `CASEDIR=...` as a workaround for 15-SP4 jobs.

2022-04-12 11:21 UTC, mdoucha requested changes
Got a reply in Bugzilla. The livepatch uname change affects only SLE-15SP4 and later. Please keep the check as is for SLE-15SP3 and earlier.

2022-04-12 14:34 UTC, mdoucha approved these changes
LGTM

2022-04-12 15:08 UTC, merged