Integrate 'chrony pid file' test of atsec into openQA
os-autoinst/os-autoinst-distri-opensuse pull request #14954
Opened 2022-05-24 02:30 UTC by Amrysliu

Related: https://progress.opensuse.org/issues/111386

2022-05-24 07:19 UTC, rfan1 approved these changes
LGTM

2022-05-25 01:15 UTC, wangqianzou requested changes

2022-05-25 02:05 UTC, Amrysliu commented on tests/security/atsec/chrony_pid_file.pm
> +    assert_script_run('systemctl start chronyd.service');
Fixed. Thanks

2022-05-27 06:04 UTC, wangqianzou approved these changes
LGTM

2022-05-27 06:24 UTC, merged