chromium: Type the first 10 characters slowly
os-autoinst/os-autoinst-distri-opensuse pull request #15004
Opened 2022-06-01 12:49 UTC by kalikiana

And type each of the first 10 characters separately.

See: https://progress.opensuse.org/issues/109737

2022-06-01 15:46 UTC, perlpunk commented on tests/x11/chromium.pm
> +    type_string substr($string, 0, 10), @_, max_interval => utils::VERY_SLOW_TYPING_SPEED;
You should be able to see my previous review comment: https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15004#pullrequestreview-991956602

I thought that the intention was to make it slower, and that changing the 3 to a 10 wasn't enough. That's why I suggested to use `VERY_SLOW_TYPING_SPEED`.

2022-06-02 09:45 UTC, kalikiana commented on tests/x11/chromium.pm
> +    type_string substr($string, 0, 10), @_, max_interval => utils::VERY_SLOW_TYPING_SPEED;
Well, exaclty this was discussed before... but let's go with just typing 10 characters slow and re-visit whenever it comes back I guess

2022-06-02 10:10 UTC, okurz approved these changes

2022-06-02 11:08 UTC, kalikiana commented
Verification run: https://openqa.opensuse.org/tests/2399415

2022-06-02 12:19 UTC, okurz approved these changes

2022-06-02 12:33 UTC, baierjan requested changes
> Verification run: https://openqa.opensuse.org/tests/2399415

Verification run failed way before the chromium module.

2022-06-02 12:56 UTC, okurz commented
> > Verification run: https://openqa.opensuse.org/tests/2399415
> 
> Verification run failed way before the chromium module.

shouldn't matter, we just type 10 characters slower rather than only 3 characters. I had already conducted tests with typing everything slower and we know that it works but also that it's slower, as expected :)

2022-06-07 13:43 UTC, kalikiana commented
> > Verification run: https://openqa.opensuse.org/tests/2399415
> 
> Verification run failed way before the chromium module.

The latest ones failed** because `zypper ref` keeps timing out: https://openqa.opensuse.org/tests/2404714

** I've run a bunch more jobs in the meanwhile and unfortunately they always fail in some unrelated way.

2022-06-07 13:50 UTC, okurz commented
So let's just merge then as already suggested in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/15004#issuecomment-1144832187

2022-06-07 13:50 UTC, merged