WIP: Add beta and exclude to img-proof
os-autoinst/os-autoinst-distri-opensuse pull request #15427
Opened 2022-08-29 09:26 UTC by grisu48

Add the beta and exclude flags to img-proof and get rid of the old list
of test runs, which should not be used anymore.

- Related ticket: https://progress.opensuse.org/issues/113818
- Verification runs: TBD

2022-08-29 12:42 UTC, pdostal approved these changes

2022-08-30 13:43 UTC, jlausuch commented on lib/publiccloud/provider.pm
> +    my $beta = $args{beta} // '0';
Why does 0 need to be a string?

```suggestion
    my $beta = $args{beta} // 0;
```
or also `undef`.

2022-09-22 13:50 UTC, asmorodskyi requested changes
we can not just run `test_sles` , it is not everything what is executed by Public Cloud devs . Just for reference compare VR which you have done for EC2 : https://duck-norris.qam.suse.de/tests/10808  and currently running https://openqa.suse.de/tests/9558910. By this PR you cutting "test_sles_ec2" for this specific run . 
So you certainly may drop lines between 18 and 26 ( where we break down to certain tests instead of alias ) but we don't want to drop all aliases and logic around which "knows" which exactly aliases needs to be run for let's say EC2 BYOS image .

Well we CAN drop it from here but only together with suggesting new place where we will keep it . Because we still need some place for that ...

2022-09-22 14:04 UTC, grisu48 commented
> we can not just run `test_sles` , it is not everything what is executed by Public Cloud devs . Just for reference compare VR which you have done for EC2 : https://duck-norris.qam.suse.de/tests/10808 and currently running https://openqa.suse.de/tests/9558910. By this PR you cutting "test_sles_ec2" for this specific run . So you certainly may drop lines between 18 and 26 ( where we break down to certain tests instead of alias ) but we don't want to drop all aliases and logic around which "knows" which exactly aliases needs to be run for let's say EC2 BYOS image .
> 
> Well we CAN drop it from here but only together with suggesting new place where we will keep it . Because we still need some place for that ...

I see. We need to adopt the settings for our test runs accordingly. I will prepare a MR for the QAC yaml that we then can merge together with this one.

2022-09-22 14:37 UTC, grisu48 commented
Related MR: https://gitlab.suse.de/qac/qac-openqa-yaml/-/merge_requests/953 (merge together!)

2022-09-26 11:35 UTC, merged