Update yamllint to produce github annotations
os-autoinst/os-autoinst-distri-opensuse pull request #15777
Opened 2022-10-25 12:28 UTC by pdostal

The current stable version of yamllint supports Github annotations
to make the warnings and errors more visible and easier to locate.

- Related ticket: [poo#118588](https://progress.opensuse.org/issues/118588)

2022-10-27 07:32 UTC, okurz requested changes
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [git-pr-last](http://github.com/okurz/scripts/tree/master/git-pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2022-10-27 12:55 UTC, foursixnine approved these changes

2022-10-27 12:56 UTC, foursixnine commented
> 

Hub is deprecated and unmantained, `gh` is the successor: https://github.com/cli/cli

2022-10-28 07:22 UTC, okurz commented
> Hub is deprecated and unmantained, `gh` is the successor: https://github.com/cli/cli

Thanks. I updated my "saved replies" now :)

2022-10-28 07:23 UTC, okurz approved these changes

2022-10-28 09:06 UTC, merged