Add rpi realhw usb keyboard emulation option.
os-autoinst/os-autoinst-distri-opensuse pull request #15800
Opened 2022-10-28 13:38 UTC by asdil12

Ticket: https://progress.opensuse.org/issues/119566

2022-10-31 10:00 UTC, okurz requested changes
If you really want to distribute such code in os-autoinst-distri-opensuse, fine, though I think including that from elsewhere is a better idea. For new files please also add a copyright and license file, same as in test modules

The git commit message subject line should not end in a dot

2022-10-31 10:10 UTC, okurz requested changes

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +uint8_t logbuf_next_idx = 0;
I recommend to use `uint_fast8_t` unless you need exactly 8 bit. Same recommendation goes for other uses of bit-fixed types.

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +  //Serial.println(logline);
Don't add disabled code as nobody but you will understand why this is not active. Better leave it out and keep in your local git repository, either in `git stash` or a temporary "WIP"-commit

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +    delay(30);
magic number, at least provide a named constant

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +    delay(500);
magic number

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +    if (i++ > 30) {
magic number

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +  char temp[8000];
magic number

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +  snprintf(temp, 7000, "<html>\
magic number

2022-10-31 10:10 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +  out.reserve(2600);
magic number

2022-11-03 11:01 UTC, okurz requested changes

2022-11-03 11:01 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/keymap.h
> +# Copyright 2022 SUSE LLC
Please avoid copyright years in newly added files

```suggestion
# Copyright SUSE LLC
```

2022-11-03 11:01 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +# Copyright 2022 SUSE LLC
same as above

2022-11-03 11:01 UTC, okurz commented on data/generalhw_scripts/rpi_pico_w_keyboard/rpi_pico_w_keyboard.ino
> +WebServer server(80);
magic number

2022-11-04 10:24 UTC, okurz approved these changes

2022-11-07 07:41 UTC, ggardet approved these changes
Awesome! I do not have RPi Pico W yet, so I cannot test, but I guess you did.

2022-11-07 10:10 UTC, merged