Add php8 tests for sles15sp5
os-autoinst/os-autoinst-distri-opensuse pull request #15824
Opened 2022-11-02 12:44 UTC by rfan1

https://progress.opensuse.org/issues/119530
Ues yaml schedule to load the tests

- Related ticket: 119530
- Verification run:[VRs for all archs]( https://openqa.suse.de/tests/overview?build=rfan&&test=rfan_php8&distri=sle&version=15-SP5)

2022-11-02 12:54 UTC, rfan1 commented
*Job setting changed as well *https://gitlab.suse.de/qsf-u/qa-sle-functional-userspace/-/merge_requests/154**

2022-11-02 13:15 UTC, pdostal requested changes
Please modify [schedule/qam/common/mau-webserver.yaml](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/schedule/qam/common/mau-webserver.yaml) instead.

2022-11-03 08:07 UTC, rfan1 commented
@pdostal Could you please help review again?

I added workaround for bsc#1204824, and fixed an issue for `conditional_schedule`

2022-11-03 15:40 UTC, pdostal commented on tests/console/curl_https.pm
> +    select_console 'root-console';
```suggestion
    serial_console::select_serial_terminal;
```

2022-11-03 15:40 UTC, pdostal commented on tests/console/php_version.pm
> +        add_suseconnect_product('sle-module-web-scripting');
Can you explain this?

2022-11-04 01:58 UTC, rfan1 commented on tests/console/php_version.pm
> +        add_suseconnect_product('sle-module-web-scripting');
sure

2022-11-04 08:24 UTC, pdostal approved these changes
Ready to be deployed.

We should just not forget about [bsc#1204824](https://bugzilla.suse.com/show_bug.cgi?id=1204824) and remove the workaround after this bug is closed.

2022-11-08 01:53 UTC, rfan1 commented
@foursixnine 
Could you please help review and merge this? 
btw, https://gitlab.suse.de/qsf-u/qa-sle-functional-userspace/-/merge_requests/154 [job group should be updated as well]

2022-11-08 08:50 UTC, merged