Move *_and_upload_ subroutines from opensusebasetest package to export_logs package
os-autoinst/os-autoinst-distri-opensuse pull request #15977
Opened 2022-11-24 15:10 UTC by pdostal

This is first of series of commits cleaning the process of gathering logs.

- Related ticket: [poo#120735](https://progress.opensuse.org/issues/120735)
- Verification run:

2022-11-25 14:18 UTC, okurz approved these changes

2022-11-26 23:47 UTC, b10n1k requested changes
I dont get it. I read the poo and i dont see how this is related to the ticket. Ticket description mentions *Decrease typing on `post_fail_hooks` log collection* (Commit title and description needs to be fixed too btw). is this a RFC or actual PR?

First question is why do you need that (it doesnt decrease typing, does it)?
Second why do you move the files into a new module and not into `Utils::Logging::`?

2022-11-28 09:32 UTC, pdostal commented
> First question is why do you need that (it doesnt decrease typing, does it)?

Before I start to work on speeding the `post_fail_hook` up I want to clean it.

> Second why do you move the files into a new module and not into `Utils::Logging::`?

Good idea! It's moved now.

@b10n1k please re-review.

2022-11-30 09:11 UTC, b10n1k requested changes
It looks better IMO. However i found some lines removed which seems to make sense in some cases, i am not sure in others. And it is hard to know the why in each case as this is a massive commit. One of the cases i am talking about is on lib/locale.pm where `export_logs_basic` is removed. I assume that this is because of post_fail_hook but still the later calls `export_logs` which is a little different process. I wonder if this is necessary on that first stage.
In addition, i would like to ask again to fix commit message and elaborate the description with some details. That will help the review as well.

2022-11-30 09:54 UTC, pdostal commented
Yes, I removed `export_logs_basic ` from `lib/locale.pm` as it is based on `opensusebasetest` which calls `export_logs` which then calls `export_logs_basic` so it makes no sense to call it twice. I am going to clean this later.

I've updated the commit message, the first verification run is finished and more are in process.

2022-11-30 20:39 UTC, foursixnine approved these changes

2022-12-01 08:11 UTC, merged