mm_network: Attempt to fix issues when we sporadically get no nameservers
os-autoinst/os-autoinst-distri-opensuse pull request #16091
Opened 2022-12-13 12:36 UTC by pdostal

As this issue is sporadic there is no easy way of debugging so I added some debug output and in case of no name server from the system we return the SUT's default gateway.

- Related ticket: [poo#121555](https://progress.opensuse.org/issues/121555)
- Verification run: [yast2_nfs_v3_client@64bit](https://pdostal-server.suse.cz/tests/3489)

2022-12-14 14:17 UTC, okurz requested changes
What you put into the description of the pull request could also be in the commit message details. I don't know how you created your pull request but your git commit messages has *only* the subject line while the pull request description has more details. Please keep in mind that the github pull request description is only visible on github, the commit can be considered permanent information storage.

I can recommend the tool [hub](https://github.com/github/hub) (zypper in rubygem-hub) for easier PR creation. Also, I myself use a script [git-pr-last](http://github.com/okurz/scripts/tree/master/git-pr-last) to create a PR with proper description for these simple one-commit PRs:
```bash
$ cat $(which git-pr-last )
#!/bin/sh -e
target="${target:-"$USER"}"
git push $target && git show --no-patch --format=%B | hub pull-request -F -
```

You might want to use the more up-to-date tool https://github.com/cli/cli

See https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md#coding-style for more details

2022-12-15 02:10 UTC, rfan1 commented on lib/mm_network.pm
> +    }
@pdostal can you and some description why you add the router ip here?

2022-12-16 01:45 UTC, rfan1 approved these changes
LGTM

2022-12-17 18:20 UTC, okurz approved these changes

2022-12-17 19:08 UTC, merged