[wip]Ci compile
os-autoinst/os-autoinst-distri-opensuse pull request #16497
Opened 2023-03-01 03:17 UTC by rfan1

[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/xyz
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

2023-03-01 08:17 UTC, grisu48 commented
I'd argue that the test should check all files to prevent that we're accidentally missing out some files and thus this should not be changed. Isn't also the CI using this test? If so, this change might reduce the overall coverage and introduce the possibility of missing out some files, that should be checked.

`test-compile-changed` is an additional convenience function to be executed locally.

2023-03-01 08:40 UTC, b10n1k requested changes
Should also this line be changed? -> https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/bebe56bb31c8baa9f4ee7e71c9adb105ac7d399b/Makefile#L118 ?

2023-03-01 09:21 UTC, foursixnine commented
> I'd argue that the test should check all files to prevent that we're accidentally missing out some files and thus this should not be changed. Isn't also the CI using this test? If so, this change might reduce the overall coverage and introduce the possibility of missing out some files, that should be checked.
> 
> IMHO `test-compile-changed` is an additional convenience function to be executed locally only.

We can do this for PRs and keep the longer running one for the merges

2023-03-01 09:32 UTC, okurz commented
> We can do this for PRs and keep the longer running one for the merges

This introduces the risk that failures in master will not be attended for long but I think that's an acceptable risk

2023-03-01 11:22 UTC, rfan1 commented
> Should also this line be changed? ->
> 
> https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/bebe56bb31c8baa9f4ee7e71c9adb105ac7d399b/Makefile#L118
> ?

done

2023-03-01 20:15 UTC, okurz requested changes
Wait, this looks wrong now. Please keep the `make test` rule as the complete one as is. Now you are making the use of "…-changed" inconsistent with other rules. If you want to only test changed files in pull requests do that explicitly but the default should be that everything is tested completely. Your change is *very* dangerous as *by default* only changed files would be compiled *but also* on merge to master not all files are compile tested.

2023-03-02 01:28 UTC, rfan1 commented
Thanks all for the kindly feedback.

I will hold on this PR due to some risks

2023-03-02 06:19 UTC, okurz commented
You can just follow the suggestion in https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16497#issuecomment-1449668278 to have the "changed" target called in GitHub actions for pull requests, the complete one otherwise. I suggest to look into the GitHub workflow file

2023-03-02 07:55 UTC, rfan1 commented
> You can just follow the suggestion in [#16497 (comment)](https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/16497#issuecomment-1449668278) to have the "changed" target called in GitHub actions for pull requests, the complete one otherwise. I suggest to look into the GitHub workflow file

Sure, will do

2023-03-03 04:14 UTC, rfan1 commented
@foursixnine Seems it is hard to define the different job for ci check for both push and pull_request, so I create a new file

2023-03-06 08:08 UTC, rfan1 commented
Based on the CI check result, comile tests  at pull_request phase is `Required`
that we can skip it.
 ci / CI: Running compile tests with perl v5.26 (pull_request) Successful in 14m **Required**

We may need change the default required workflow [I don't have the permission to do this]
 https://docs.github.com/en/actions/using-workflows/required-workflows

2025-03-19 14:16 UTC, michaelgrifalconi commented
Hello @okurz , trying to resume this topic to finally close it. I see it was agreed to have both compile and compile-changed running, where only compile-changed mandatory (while now the full compile is).
Is this still fine?

If yes, I would propose to get this PR merged and then have someone with admin permission in this repo to remove 'compile' test from the Required ones to merge PRs.

2025-03-20 07:54 UTC, okurz approved these changes

2025-03-21 08:17 UTC, michaelgrifalconi commented
For the record, the force push was with no changes, to trigger github checks again, which were stuck.

2025-03-21 08:17 UTC, merged