Add podman kube generate test
os-autoinst/os-autoinst-distri-opensuse pull request #16560
Opened 2023-03-07 12:27 UTC by ilausuch

- Related ticket: https://progress.opensuse.org/issues/124601
- Verification run:

2023-03-07 15:48 UTC, pdostal requested changes
Maybe you can also save the yaml, remove the container and apply the yaml and then run the container so we're sure it's valid?

Also maybe you can also actually create a pod and place the container in it? E.g:
```bash
podman pod create testing_pod
podman container create --pod testing_pod --name generate_test …
```
But I'm not forcing you of course, that are just ideas.

2023-03-07 15:48 UTC, pdostal commented on tests/containers/podman_pods.pm
> +    my $pod_id = script_output('podman ps -a | grep generate_test | cut -d " " -f1');
```suggestion
    my $container_id = script_output('podman container inspect generate_test --format "{{.Id}}"');
```

2023-03-08 10:22 UTC, ilausuch commented on tests/containers/podman_pods.pm
> +    my $pod_id = script_output('podman ps -a | grep generate_test | cut -d " " -f1');
Thanks are good ideas

2023-03-08 10:57 UTC, ilausuch commented on tests/containers/podman_pods.pm
> +    my $pod_id = script_output('podman ps -a | grep generate_test | cut -d " " -f1');
done

2023-03-09 12:34 UTC, ilausuch commented
I implemented your ideas. Thank you

2023-03-09 12:48 UTC, pdostal approved these changes
Awesome 🤩

2023-03-21 10:12 UTC, ilausuch commented on tests/containers/podman_pods.pm
> +    assert_script_run('podman pod ps | grep "testing_pod"');
I will change grep by validate_script_output

2023-03-29 11:40 UTC, ricardobranco777 approved these changes
LGTM

2023-03-29 12:20 UTC, jlausuch reviewed
Looks good! Maybe we could use `script_retry` to pull the image just in case?

So, if I understand correctly , `podman kube play pod.yaml` and `podman play kube pod.yaml` does the same thing?

2023-03-29 12:23 UTC, pdostal reviewed
Is that intentional to heve `podman kube plan` in one block and `podman play kube` in another? Maybe you can somehow describe it in `record_info()`

2023-03-29 12:23 UTC, pdostal commented on tests/containers/podman_pods.pm
> +        record_info('Test', 'Killing one pod');
```suggestion
        record_info('Test', 'Removing one pod');
```

2023-03-29 12:25 UTC, ilausuch commented on tests/containers/podman_pods.pm
> +        assert_script_run('podman container create --pod testing_pod --name container registry.suse.com/bci/python:latest bash -c "while true; do sleep 1; done"');
good point, thanks!

2023-03-29 12:25 UTC, ilausuch commented
Thanks for the reviews

2023-03-29 12:26 UTC, pdostal commented on tests/containers/podman_pods.pm
> +        assert_script_run('podman container create --pod testing_pod --name container registry.suse.com/bci/python:latest bash -c "while true; do sleep 1; done"');
```suggestion
        my $image = 'registry.suse.com/bci/python:latest';
        script_retry "podman image $image";
        assert_script_run("podman container create --pod testing_pod --name container $image bash -c 'while true; do sleep 1; done'");
```

2023-03-29 12:32 UTC, ricardobranco777 requested changes
We could use `bci-busybox` instead of `python:3.10` as the image is much shorter:

```
$ podman images
REPOSITORY                           TAG         IMAGE ID      CREATED       SIZE
registry.suse.com/bci/bci-busybox    latest      8479bde8aeb3  5 weeks ago   14.4 MB
registry.suse.com/bci/python         3.10        45eb3f9210d9  5 weeks ago   235 MB
```

2023-03-30 09:44 UTC, ricardobranco777 requested changes

2023-03-30 09:44 UTC, ricardobranco777 commented on tests/containers/podman_pods.pm
> +        assert_script_run("podman container create --pod testing_pod --name container image sh -c \"while true; do sleep 3600; done\"");
```suggestion
        assert_script_run("podman container create --pod testing_pod --name container $image sleep 3600");
```
You forgot the `$` :)

Also, I think we can drop the `while` loop and just use `sleep 3600` as we don't expect the container to run that longer.

2023-03-30 10:11 UTC, ilausuch commented
I am testing yet.. I will notify when is ready again :)

2023-03-30 11:39 UTC, ricardobranco777 approved these changes
Just a small suggestion. Otherwise LGTM

2023-03-30 11:39 UTC, ricardobranco777 commented on tests/containers/podman_pods.pm
> +        assert_script_run("podman container create --pod testing_pod --name container $image sh -c \"sleep 3600\"");
```suggestion
        assert_script_run("podman container create --pod testing_pod --name container $image sleep 3600");
```
You don't really need the `sh` to run `sleep` :)

2023-03-30 13:20 UTC, jlausuch approved these changes

2023-03-30 14:07 UTC, merged