Restart firewalld only if active
os-autoinst/os-autoinst-distri-opensuse pull request #17550
Opened 2023-08-08 16:35 UTC by grisu48

Restart the firewall only if it was previously already active to avoid (bsc#1214080)[https://bugzilla.suse.com/show_bug.cgi?id=1214080]

- Related ticket: https://progress.opensuse.org/issues/133808
- Verification run: https://openqa.opensuse.org/tests/3492898

2023-08-08 16:43 UTC, ricardobranco777 requested changes
I would add a soft-fail with the link to the bug you opened: https://bugzilla.suse.com/show_bug.cgi?id=1214080

At the very least a comment on why this is necessary.

2023-08-09 06:48 UTC, mloviska commented
> I would add a soft-fail with the link to the bug you opened: https://bugzilla.suse.com/show_bug.cgi?id=1214080
> 
> At the very least a comment on why this is necessary.
> 
> Otherwise LGTM.

Agreed, I would also add the podman related bug

2023-08-09 06:53 UTC, grisu48 commented
> I would add a soft-fail with the link to the bug you opened: https://bugzilla.suse.com/show_bug.cgi?id=1214080
> 
> At the very least a comment on why this is necessary.
> 
> Otherwise LGTM.

Agreed, it becomes obvious that we need to reference the two softfailures. Since those two bsc are not easy to trigger (require specific environment setup), I'll move them to a separate test. It does not make sense to add a softfailure everywhere where we apply those workaround because they are omnipresent.

Let's move forward with this PR and I will add corresponding softailures in an additional test run for the container engine?

2023-08-09 06:56 UTC, ricardobranco777 approved these changes
LGTM

2023-08-09 06:56 UTC, merged