Public Cloud: Test the python-instance-billing-flavor-check package
os-autoinst/os-autoinst-distri-opensuse pull request #17638
Opened 2023-08-23 13:00 UTC by pdostal

The package is currently available only for AWS.

- Related ticket: [poo#133085](https://progress.opensuse.org/issues/133085)
- Verification run: TBD

2023-08-23 13:03 UTC, ricardobranco777 requested changes

2023-08-23 13:03 UTC, ricardobranco777 commented on lib/main_publiccloud.pm
> +            loadtest "publiccloud/flavor_check" if(is_ec2());
```suggestion
            loadtest "publiccloud/flavor_check" if (is_ec2());
```

2023-08-23 13:03 UTC, ricardobranco777 commented on tests/publiccloud/flavor_check.pm
> +# Copyright 2021 SUSE LLC
```suggestion
# Copyright 2023 SUSE LLC
```

2023-08-23 13:03 UTC, ricardobranco777 commented on tests/publiccloud/flavor_check.pm
> +    script_run('cat /var/log/instance_billing_flavor_check');
I would use a variable for this path and use upload_logs() if possible.

2023-08-23 13:07 UTC, grisu48 approved these changes
Ok from my side with @ricardobranco777 suggestions being implemented.

2023-08-23 13:08 UTC, ricardobranco777 commented on tests/publiccloud/flavor_check.pm
> +    script_run('cat /var/log/instance_billing_flavor_check');
Ok.  Let's use a variable for the path as it's long.

2023-08-23 13:28 UTC, pdostal commented
Setting as WIP so it's not merged before the [SLE15 incident](http://dashboard.qam.suse.de/incident/29847) gets released.

2023-08-28 10:26 UTC, asmorodskyi commented on tests/publiccloud/flavor_check.pm
> +        validate_script_output('instance-flavor-check', sub { m/^BYOS$/m }, proceed_on_failure => 1, fail_message => "The command did not return 'BYOS'.");
I think you can tweak code for single run to simulate such case e.g. 
```suggestion
        validate_script_output('instance-flavor-check', sub { m/^NOMATCH$/m }, proceed_on_failure => 1, fail_message => "The command did not return 'BYOS'.");
```

2023-08-28 10:28 UTC, asmorodskyi commented
generally OK , but I have doubts about first `validate_script_output` ( probably simply luck of knowledge how openQA behaves in such situation )

2023-08-28 10:31 UTC, pdostal commented on tests/publiccloud/flavor_check.pm
> +        validate_script_output('instance-flavor-check', sub { m/^BYOS$/m }, proceed_on_failure => 1, fail_message => "The command did not return 'BYOS'.");
I'm checking that the command `instance-flavor-check` returns `BYOS`, e.g.:
```bash
$ instance-flavor-check
BYOS
```
the `fail_message` parameter will get triggered only if the `validate_script_output` will fail to validate the snippet above.

2023-08-28 10:38 UTC, asmorodskyi approved these changes
LGTM

2023-08-28 11:11 UTC, pdostal commented on tests/publiccloud/flavor_check.pm
> +        validate_script_output('instance-flavor-check', sub { m/^BYOS$/m }, proceed_on_failure => 1, fail_message => "The command did not return 'BYOS'.");
Please check now.

The `proceed_on_failure => 1` is there to not check the return code as it's never `0` and it's checked later.

2023-08-29 11:31 UTC, merged