Prevent warewulf client from booting
os-autoinst/os-autoinst-distri-opensuse pull request #17711
Opened 2023-09-06 07:59 UTC by b10n1k

If ipxe fails tries to boot. assert qemu-no-bootable-device and make the sut waiting in the ipxe shell before try again.

- Related ticket: https://progress.opensuse.org/issues/135218
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

2023-09-06 09:12 UTC, czerw commented
This is not correct and we already discussed it in the past. Just remove ISO variable from client test suites to don't boot from it.

2023-09-06 09:13 UTC, czerw commented
Really don't understand why are we going in loops with HPC see https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/17316

2023-09-06 09:35 UTC, czerw commented
See https://progress.opensuse.org/issues/135218#note-2

2023-09-06 09:38 UTC, schlad requested changes
I think @czerw is having a point.

2023-09-06 13:25 UTC, b10n1k commented
> This is not correct and we already discussed it in the past. Just remove ISO variable from client test suites to don't boot from it.

you are likely right. i find the ISO defined. Maybe from my mistake but that got me confused. ignore and i will close it once i verify it.
But maybe it is better to keep it like that and do not mess with the variables. not sure

2023-09-07 06:42 UTC, czerw commented
>  But maybe it is better to keep it like that and do not mess with the variables. not sure

It's definitely not better as it would be same like original approach.  Pressing CTRl+B  will not help  when machine boots to ISO. The only one correct approach is to don't specify  ISO to avoid booting from the image.

2023-09-15 20:06 UTC, closed without merging