Skip wait_boot for autoyast installations
os-autoinst/os-autoinst-distri-opensuse pull request #17721
Opened 2023-09-07 10:02 UTC by frankenmichl

When we deploy the system with autoyast, there is no reboot after the installation and wait_boot never sees a grub menu, so let's skip this in this case.

This will fix https://openqa.suse.de/tests/11998046 and similar

2023-09-07 15:59 UTC, mdoucha commented on tests/autoyast/console.pm
> +    $self->wait_boot if is_ipmi && !get_vat('AUTOYAST');
Typo.

2023-09-08 11:02 UTC, mdoucha commented
Verification run: https://openqa.suse.de/tests/12048649

2023-09-08 13:10 UTC, Martchus commented on tests/autoyast/console.pm
> +    $pxe_boot_done = 1 if (check_var('IPXE', '1') || check_var('IPXE_UEFI', '1'));
```suggestion
    my $pxe_boot_done = check_var('IPXE', '1') || check_var('IPXE_UEFI', '1');
```

2023-09-08 13:10 UTC, Martchus commented on tests/autoyast/console.pm
> +    $self->wait_boot if is_ipmi and not get_var('VIRT_AUTOTEST') and not $pxe_boot_done;
Normally the symbolic operators are preferred (unless you do command chaining):
```suggestion
    $self->wait_boot if is_ipmi && !get_var('VIRT_AUTOTEST') && !$pxe_boot_done;
```

2023-09-08 13:53 UTC, frankenmichl commented on tests/autoyast/console.pm
> +    $pxe_boot_done = 1 if (check_var('IPXE', '1') || check_var('IPXE_UEFI', '1'));
Good suggestion, thanks!

2023-09-08 14:33 UTC, mdoucha requested changes

2023-09-08 14:34 UTC, mdoucha commented on tests/autoyast/console.pm
> +    $self->wait_boot if is_ipmi && !get_var('VIRT_AUTOTEST') && !$pxe_boot_done;
For non-IPMI jobs, there should be no `wait_boot` call in either module.

2023-09-08 14:43 UTC, mdoucha commented on tests/autoyast/console.pm
> +    $self->wait_boot if is_ipmi && !get_var('VIRT_AUTOTEST') && !$pxe_boot_done;
Hmm, no, never mind. On second thought, this is probably correct as is.

2023-09-08 14:45 UTC, mdoucha commented
@Julie-CAO Please have a look whether this will work correctly with VIRT_AUTOTEST.

2023-09-11 01:57 UTC, Julie-CAO commented
> @Julie-CAO Please have a look whether this will work correctly with VIRT_AUTOTEST.

thanks for asking. `tests/autoyast/console.pm`  is not called by virt tests, so VIRT_AUTOTEST is not required here.

2023-09-11 07:44 UTC, frankenmichl commented
So we can keep this a bit simpler

2023-09-11 08:23 UTC, Martchus approved these changes

2023-09-11 08:29 UTC, mdoucha approved these changes
The first comment is redundant but otherwise LGTM.

2023-09-11 08:36 UTC, Martchus commented
Yes, the commits should be squashed. You can do this directly on GitHub when merging.

2023-09-12 06:06 UTC, frankenmichl commented
New verification run: https://openqa.suse.de/tests/12091394

2023-09-15 12:01 UTC, merged