Improve test container runtime privileged mode
os-autoinst/os-autoinst-distri-opensuse pull request #17891
Opened 2023-10-02 11:48 UTC by ilausuch

- Related ticket: https://progress.opensuse.org/issues/135518
- Verification run:

2023-10-02 13:13 UTC, ricardobranco777 requested changes

2023-10-02 13:13 UTC, ricardobranco777 commented on tests/containers/privileged_mode.pm
> +    assert_script_run("$runtime run --rm --privileged $image cat /proc/1/cgroup");
Unprivileged and privileged containers have the same content on this file.

2023-10-02 13:13 UTC, ricardobranco777 commented on tests/containers/privileged_mode.pm
> +    assert_script_run("! $runtime run --rm --privileged --read-only $image touch /test", fail_message => "Nope");
Touching a file have the same effect on privileged and unprivileged containers.

2023-10-03 07:10 UTC, ilausuch commented
Yes, this PR doesn't have any sense. I ran this in unprivileged mode and worked http://openqa.suse.de/tests/12359882#
I close this

2023-10-03 07:10 UTC, closed without merging