Refactor subroutine which creates xml result file
os-autoinst/os-autoinst-distri-opensuse pull request #18021
Opened 2023-10-18 12:58 UTC by b10n1k

Move the parsing and the creation of the xml out of the SUT. As such we do not repeat the script_run script which might make the runtime a bit faster overall.
In addition I added date and build elements in the xml as additional info of the test results which i think will help in the review of the tests.

- Related ticket: https://progress.opensuse.org/issues/127673
- Verification run:

2023-10-18 14:42 UTC, b10n1k commented on lib/utils.pm
> +sub create_xml_results {
obviously the pars_result should be parse_results. But I thought to change it as part of this PR and considering what exactly the function is doing. i couldnt think anything else as well. But i think it is very accurate. i wonder what do you think it should be based on its functionality

2023-10-22 14:40 UTC, schlad requested changes
Stop writing such stuff in the git commit messages: "which i think will help in the review of the tests."
Not to mention one does not write "i" but "I".
In any case as discussed and pointed before: git commit message should not be written in a personal form "I did/I think etc."

2023-10-22 14:47 UTC, schlad commented on lib/utils.pm
> +sub create_xml_results {
ultimately this is the main thing:
if ($i->{result} eq 'FAIL') {
            $tc_elem->setAttribute(error => '1');

so this is the test result parser. I would prefer you change the name to the pars_test_results

2023-10-23 07:17 UTC, b10n1k commented
> Stop writing such stuff in the git commit messages: "which i think will help in the review of the tests." Not to mention one does not write "i" but "I". In any case as discussed and pointed before: git commit message should not be written in a personal form "I did/I think etc."

Updated

2023-10-24 06:44 UTC, b10n1k commented on lib/utils.pm
> +sub create_xml_results {
`pars_test_results` or `parse_test_results`?

2023-10-25 09:09 UTC, schlad approved these changes

2023-10-25 09:35 UTC, merged