Add GTK4 and QT6 to toolkit testsuite
os-autoinst/os-autoinst-distri-opensuse pull request #18020
Opened 2023-10-18 12:21 UTC by asdil12

2023-10-18 21:02 UTC, foursixnine approved these changes
We really need to do something about compressed tarballs...

2023-10-19 05:07 UTC, okurz commented on tests/x11/toolkits/gtk4.pm
> +# Copyright 2024 SUSE LLC
For new files you can just leave out the Copyright year. It's wrong anyway :D

2023-10-19 06:46 UTC, okurz requested changes

2023-10-19 06:46 UTC, okurz commented on tests/x11/toolkits/prepare.pm
>  # SPDX-License-Identifier: FSFAP
Keep the old, see https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/CONTRIBUTING.md

2023-10-19 06:46 UTC, okurz commented on tests/x11/toolkits/qt6.pm
> +# Copyright 2024 SUSE LLC
Delete year

2023-10-19 06:46 UTC, okurz commented on tests/x11/toolkits/qt6.pm
> +    enter_cmd "exit";
```suggestion
    enter_cmd 'exit';
```

2023-10-19 08:44 UTC, okurz requested changes

2023-10-19 08:44 UTC, okurz commented on tests/x11/toolkits/gtk4.pm
> +    enter_cmd "exit";
```suggestion
    enter_cmd 'exit';
```

2023-10-19 08:44 UTC, okurz commented on data/toolkits/fltk.cc
> +#include <FL/Fl.H>
Please add the copyright+license in these source files as well

2023-10-19 10:11 UTC, okurz approved these changes

2023-10-19 11:24 UTC, merged

2023-10-20 12:33 UTC, DimStar77 commented
Those two new tests - appearing the first time in TW, are both failing:

https://openqa.opensuse.org/tests/3660785 - qt6 and gtk4 failing

2023-10-20 12:37 UTC, DimStar77 commented
> VR: https://openqa.opensuse.org/tests/3655158

The VR is two days old and not based on the latest code submission. Even the close of the VR is only 819f12e - quite a few force-pushes happened after that

2023-10-20 14:42 UTC, DimStar77 commented
> > VR: https://openqa.opensuse.org/tests/3655158
> 
> The VR is two days old and not based on the latest code submission. Even the close of the VR is only [819f12e](https://github.com/os-autoinst/os-autoinst-distri-opensuse/commit/819f12e4b20b062dad15a18dec78810dc3bbcdf2) - quite a few force-pushes happened after that

The VR is fine - just that the VR was only running on GNOME (where it passes) but was not running on KDE - possibly missing needles (but the screens do not really look like the toolkit's dialogs should look like)

2023-10-23 10:16 UTC, asdil12 commented
That simple hello world labels/buttons look fine. Just the needles for the theme used on kde were missing.
I added the needles and restarted the latest kde test.