containers: cni issue in volumes_podman tests
os-autoinst/os-autoinst-distri-opensuse pull request #18624
Opened 2024-02-08 19:54 UTC by m-dati

A container network issue impacted `volumes_podman` in `slem_containers_selinux` tests of group [532](https://openqa.suse.de/group_overview/532), after **cni** and **neavark** modules run. Some check have been added, to introduce resilience.

- Related ticket: https://progress.opensuse.org/issues/137168
- Needles: N/A
- Verification run: https://openqa.suse.de/tests/13473070

2024-02-08 22:10 UTC, ricardobranco777 requested changes
This is not an issue in the `volumes_podman` module and this PR just masks the problem.  Any module that runs after `podman_netavark` will have the same issue.

The error message suggests it may be related to this bug:
https://bugzilla.opensuse.org/show_bug.cgi?id=1218004

Another weird thing is that the failed test for SLEM 5.5 pulled netavark when installing podman as you can see in the [serial log](https://openqa.suse.de/tests/13460022/logfile?filename=serial_terminal.txt), yet [this function](https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/master/tests/containers/podman_netavark.pm#L25) asserts that CNI is default.

2024-02-09 09:42 UTC, m-dati commented
> This is not an issue in the `volumes_podman` module and this PR just masks the problem. Any module that runs after `podman_netavark` will have the same issue.
> 
> The error message suggests it may be related to this bug: https://bugzilla.opensuse.org/show_bug.cgi?id=1218004
> ...

First thing I wish to clarify, This PR is NOT masking any issue, BUT instead to introduce _general_ check function(s), in `utility`, for generic verification and resilience of containers runtimes, that can be used everywere needed an initial or final run-status check.

Such containers routine indeed could be called even i.e. at start or end of netavark or cni modules other than in `volumes`.  I can agree that it should offer 2 ways, default detection and additional reset mode, that I can soon add.

Then let we remember that `is_cni_default` is based on a static version check and not a current-status system check able to exactly detect the real network configuration and the status of the system.

So, just because of bug#1218004 is around, IMHO _this routine_ could be useful if used in any test as initial or final container-working base verification.

Finally, this PR introduces also a test-function using positive-logic in perl code test in place of the shell inverted-logic checks.

I'll try some more code-changes to convince you to remove the PR-lock, but a wider discussion inside our team is here really needed, to decide next step: WDYT @pdostal @grisu48 @asmorodskyi @mloviska ?

2024-02-09 11:05 UTC, ricardobranco777 commented
> So, just because of bug#1218004 is around, IMHO _this routine_ could be useful if used in any test as initial or final container-working base verification.

This kind of test, if needed at all, belong in each engine's test module and not in a library.

> Finally, this PR introduces also a test-function using positive-logic in perl code test in place of the shell inverted-logic checks.

This should be dropped.  First because it's not needed and second because it's unreadable Perl.

2024-02-09 14:22 UTC, m-dati commented
Check routines updated: call moved away from volumes in podman_netavark::_cleanup; definition location can be moved where eventually suggested.

2024-02-09 14:44 UTC, m-dati commented
VR https://openqa.suse.de/tests/13483456

2024-02-09 14:45 UTC, ricardobranco777 commented
> Check routines updated and call moved away from _volumes_ in _podman_netavark::_cleanup_; definition location can be moved everywhere eventually suggested.

There are still at least 7 problems:
1. check_podman() & check_docker() have duplicated code.  Having a single function that handle both runtimes is better.
1. The function does a lot more than the name suggests.
1. The `reset` parameter name is _wrong_ as it doesn't run `docker|podman` reset` but prunes images instead, which is not a reset.
1. You're not using our registry mirror for the hello-world image, which _will_ bring issues with the Docker Registry pull limits.  See how the `registry_url` function is used.
1. The introduction of a `is_sh_ok` function in a library when it's used by ideally one function.
1. It's still masking a test setup issue where having to prune images somehow "fixes" a network related module.  You're adding all this code just to run it in `containers/podman_netavark`, but it's this module that needs fixing instead.

2024-02-12 10:13 UTC, m-dati commented
As asked in the [Slack thread](https://suse.slack.com/archives/C02CGKBCGT1/p1707732235798339?thread_ts=1707730698.539829&cid=C02CGKBCGT1), this PR is **CANCELLED**.

2024-02-12 10:16 UTC, m-dati commented
Let's see whether other PC SLEM versions <5.5 have the same issue too: PR Closed.

2024-02-12 10:16 UTC, closed without merging