Delete ALP references
os-autoinst/os-autoinst-distri-opensuse pull request #18910
Opened 2024-03-18 20:36 UTC by jlausuch

2024-03-20 08:41 UTC, grisu48 reviewed
Reviewed it for QE-C. Some minor comments, overall nothing worrysome.

2024-03-20 08:41 UTC, grisu48 commented on tests/console/ansible.pm
> +$pkgs .= ' python3-yamllint';
Please merge with line above.

2024-03-20 08:41 UTC, grisu48 commented on tests/jeos/firstrun.pm
> +    # Only execute this block on SLE Micro when using the encrypted image.
```suggestion
    # Only execute this block on SLE Micro 6+ when using the encrypted image.
```

2024-03-20 08:41 UTC, grisu48 commented on tests/kernel/install_ltp.pm
> +    zypper_call('in efivar') if is_sle('12+') || is_opensuse;
```suggestion
    if (is_transactional) {
        assert_script_run("transactional-update -n -c pkg install efivar", 90);
    } else {
        zypper_call('in efivar') if is_sle('12+') || is_opensuse;
    }
```

WDYT?

2024-03-20 11:40 UTC, jlausuch commented on tests/console/ansible.pm
> +$pkgs .= ' python3-yamllint';
done, thanks!

2024-03-20 11:43 UTC, jlausuch commented on tests/kernel/install_ltp.pm
> +    zypper_call('in efivar') if is_sle('12+') || is_opensuse;
changed, thx

2024-03-20 11:43 UTC, jlausuch commented on tests/jeos/firstrun.pm
> +    # Only execute this block on SLE Micro when using the encrypted image.
done

2024-03-20 14:34 UTC, czerw approved these changes
LGTM

2024-03-21 02:46 UTC, SeroSun approved these changes
LGTM, verify run for xfstests installation passed https://openqa.suse.de/tests/13827307

2024-03-22 09:10 UTC, jlausuch commented
> LGTM, verify run for xfstests installation passed https://openqa.suse.de/tests/13827307

Thanks Sero.

2024-03-22 10:36 UTC, jknphy approved these changes

2024-03-22 18:32 UTC, ricardobranco777 approved these changes

2024-03-26 07:28 UTC, tjyrinki requested changes

2024-03-26 07:28 UTC, tjyrinki commented on schedule/security/alp/container_selinux.yaml
Hi. Please do not delete schedule/security/alp, as they mean "alp as in codebase" and are used for SLE Micro. Otherwise all good.

2024-03-26 10:32 UTC, jlausuch commented on schedule/security/alp/container_selinux.yaml
sure, I will put it back

2024-03-26 11:37 UTC, jlausuch commented on schedule/security/alp/container_selinux.yaml
Done. It would be nice to rename the directory later on, but I leave it up to you :)

2024-03-27 05:35 UTC, tjyrinki commented on schedule/security/alp/fde_misc.yaml
So leave this one too.

2024-03-27 05:36 UTC, tjyrinki commented on schedule/security/alp/fips_crypt_core.yaml
And this one.

2024-03-27 05:37 UTC, tjyrinki commented on schedule/security/alp/container_selinux.yaml
Sorry, I only commented on the first of the three files, but indeed Meant the whole schedule/security/alp - all of those are referenced in our job groups. I agree on the renaming, let's see what'll be a proper final name depending on which products those schedules will be used for.. I'll create a ticket, maybe just about renaming it to slemicro.

2024-03-27 10:46 UTC, jlausuch commented on schedule/security/alp/container_selinux.yaml
Sorry, I missunderstood. Now the 3 files are back :)

2024-03-28 06:50 UTC, tjyrinki commented on schedule/security/alp/container_selinux.yaml
Thank you!

2024-03-28 06:51 UTC, tjyrinki approved these changes
Looks good now!

2024-03-28 08:47 UTC, jlausuch commented
Rebased

2024-03-28 09:04 UTC, merged

2024-03-29 08:40 UTC, DimStar77 commented
That seems to be the reason for https://openqa.opensuse.org/tests/4050338

```
[2024-03-29T06:31:01.753644Z] [debug] [pid:7401] YAML_SCHEDULE file not found: 'microos/lib/../schedule/alp/bonding.yaml'
[2024-03-29T06:31:01.755936Z] [warn] [pid:7401] !!! main: Provided YAML_SCHEDULE does not exist at microos/lib/scheduler.pm line 173.
```

2024-03-29 08:40 UTC, DimStar77 commented
![image](https://github.com/os-autoinst/os-autoinst-distri-opensuse/assets/532559/6dc61382-651c-4260-ba9a-33b401a62228)