Define new name for the project *osado*
os-autoinst/os-autoinst-distri-opensuse pull request #19445
Opened 2024-06-03 12:27 UTC by okurz

The new name is based on a brainstorming conducted within a SUSE Slack
conversation with vote. The most promising alternatives had been:
* arepa
* osdo
* oto

2024-06-03 12:58 UTC, foursixnine requested changes
os-autoinst-distri-opensuse contains far more than the tests, and is more of a test distribution than a collection of tests.

2024-06-03 12:58 UTC, foursixnine commented on README.md
> +contains tests, which are executed by openQA for openSUSE and SLE
```suggestion
*osado* – or with long name *os-autoinst-distri-opensuse* – is repo which
contains the [test distribution](https://en.wikipedia.org/wiki/Software_distribution) of the suite and harness, executed by openQA for openSUSE and SLE
```

2024-06-06 09:12 UTC, m-dati approved these changes

2024-06-07 09:02 UTC, foursixnine approved these changes

2024-06-07 09:02 UTC, merged