Softfail for bsc#1220722
os-autoinst/os-autoinst-distri-opensuse pull request #19790
Opened 2024-07-22 13:43 UTC by foursixnine

2024-07-22 13:57 UTC, foursixnine commented
I don't have openqa clone thing in this machine, and I'm not sure the clonning with comments work for osd, @jlausuch can you give me a hand? https://openqa.suse.de/tests/14939950

cc @Martchus ^ would that work? if yes: where is it documented?

2024-07-26 07:04 UTC, jlausuch commented
> I don't have openqa clone thing in this machine, and I'm not sure the clonning with comments work for osd, @jlausuch can you give me a hand? https://openqa.suse.de/tests/14939950
> 
> cc @Martchus ^ would that work? if yes: where is it documented?

with this branch: http://openqa.suse.de/tests/15006311

2024-07-26 07:23 UTC, jlausuch requested changes
It also happens in 6.1

2024-07-26 07:23 UTC, jlausuch commented on tests/microos/image_checks.pm
> +    if (is_sle_micro("6.0") && is_aarch64 && get_var("HDD_1") =~ /qcow2/) {
```suggestion
    if (is_sle_micro('>=6.0') && is_aarch64 && get_var("HDD_1") =~ /qcow2/) {
```

2024-07-26 09:36 UTC, jlausuch commented
New VR: https://openqa.suse.de/tests/15007273#step/image_checks/10

2024-07-26 09:36 UTC, jlausuch approved these changes
LGTM

2024-07-26 09:36 UTC, merged