Do not create user if exists
os-autoinst/os-autoinst-distri-opensuse pull request #20212
Opened 2024-09-18 06:24 UTC by rfan1

https://progress.opensuse.org/issues/166175

[Verification run](https://openqa.suse.de/tests/overview?build=rfan0918&version=15-SP7&distri=sle)

2024-09-18 06:38 UTC, Vogtinator requested changes
IMO that's the wrong approach.

If it's not possible to fix the testing to avoid running the firstboot wizard twice, it should be made much more explicit which "stage" it is running instead of just doing the same things twice.

2024-09-18 06:38 UTC, Vogtinator commented on tests/jeos/firstrun.pm
> +my $user_created = check_var('BACKEND', 'generalhw') ? 1 : 0;
There is no obvious connection from `check_var('BACKEND', 'generalhw')` to "user was already created".

2024-09-18 06:38 UTC, Vogtinator commented on tests/jeos/firstrun.pm
> +    if (is_s390x || check_var('BACKEND', 'generalhw') || (is_aarch64 && get_var('HDD_1') =~ /.*raw\.xz$/ && !is_community_jeos)) {
There is no connection from `check_var('BACKEND', 'generalhw')` to "uses MBR". What about non RPi?

2024-09-19 00:57 UTC, rfan1 commented
> IMO that's the wrong approach.
> 
> If it's not possible to fix the testing to avoid running the firstboot wizard twice, it should be made much more explicit which "stage" it is running instead of just doing the same things twice.
> 

 Added a setting then.

2024-09-20 10:06 UTC, jlausuch requested changes
I would suggest fixing the schedule so that the module is not executed on the children.

2024-09-20 10:25 UTC, rfan1 commented
> Can't we just use `EXCLUDE_MODULES=firstrun` in the children jobs?

I tried, but seems some key steps are missing to run next modules

2024-09-20 10:29 UTC, Vogtinator commented
> Can't we just use EXCLUDE_MODULES=firstrun in the children jobs?

Technically yes - but IMO it makes sense to test jeos-firstboot on the actual target hardware.

2024-09-23 06:23 UTC, rfan1 commented
> I would suggest fixing the schedule so that the module is not executed on the children.

Without this module, we may not able to entn

> I would suggest fixing the schedule so that the module is not executed on the children.

Without this module, seems root account and password creation will be missed like https://openqa.suse.de/tests/15462356#step/firstrun/8

2024-09-23 11:14 UTC, rfan1 commented
@Vogtinator has done for partition part https://github.com/os-autoinst/os-autoinst-distri-opensuse/pull/20247
Let me move this to draft status, and talk with Jose offline for next step

2025-05-06 06:36 UTC, closed without merging