WIP Add snapper-zypp-plugin test
os-autoinst/os-autoinst-distri-opensuse pull request #20618
Opened 2024-11-13 09:54 UTC by cedvid

https://progress.opensuse.org/issues/168079

[type description here, PLEASE, REMOVE THIS LINE, PLACEHOLDER, BEFORE SUBMITTING THIS PULL REQUEST]

- Related ticket: https://progress.opensuse.org/issues/xyz
- Needles: https://github.com/os-autoinst/os-autoinst-needles-opensuse/pull/xyz
- Verification run: openqa.mypersonalinstance.de/tests/xyz#step/module/x

2025-01-17 08:26 UTC, Vogtinator commented on tests/console/snapper_zypp.pm
> +    assert_equals($after_snapshot_id, $before_snapshot_id + 2, "Snapshot ID did not increment as expected");
You could also check that `snapper diff` has some output or that `/.snapshots/$snap/snapshot/usr/bin/vi` exists in one but not the other.

2025-01-17 08:28 UTC, Vogtinator requested changes
Please double-check that it works on JeOS, e.g. https://openqa.opensuse.org/tests/4779041

2025-01-17 08:28 UTC, Vogtinator commented on tests/console/snapper_zypp.pm
> +    my $package = "vim";
This might not work on JeOS which has `vim-small` instead.

2025-01-20 08:35 UTC, cedvid commented on tests/console/snapper_zypp.pm
> +    my $package = "vim";
Noted, thanks. I added the verification run for JeOS

2025-01-20 09:19 UTC, merged